import {useEffect,useMemo,useState} from "react";
import {ArrowLeft,ChevronDown,Image,MessageCircle,Search,Star,Sticker,Volume2} from "lucide-react";
import {Navigate,useNavigate,useParams,useSearchParams} from "react-router-dom";
import {conversationDisplayName} from "../core/conversationSettings";
import {searchableMessageText,searchChatMessages,type ChatSearchResult} from "../core/chatSearch";
import {readConversationMessagePage,type MessageCursor} from "../core/messageStore";
import {useStore} from "../core/store";
import type {Message} from "../core/types";

type FavoriteCategory="all"|"chat"|"media"|"voice";
function messageCategory(message:Message):Exclude<FavoriteCategory,"all">{const type=message.attachments?.[0]?.type;return type==="voice"?"voice":type==="image"||type==="sticker"?"media":"chat"}
function kindIcon(message:Message,favorite=false){if(favorite)return <Star/>;const type=message.attachments?.[0]?.type;if(type==="image")return <Image/>;if(type==="sticker")return <Sticker/>;if(type==="voice")return <Volume2/>;return <MessageCircle/>}
function favoriteTitle(message:Message,summary:string){const type=message.attachments?.[0]?.type;if(type==="voice"){const voice=message.attachments?.find(item=>item.type==="voice");return voice&&voice.type==="voice"?`${Math.max(1,Math.round(voice.durationMs/1000))} 秒语音`:"语音消息"}if(type==="image")return"收藏的图片";if(type==="sticker")return"收藏的表情包";return summary.split(/\r?\n/).find(Boolean)?.slice(0,34)||"收藏的聊天消息"}

export default function ChatSearchPage(){
 const {id}=useParams(),nav=useNavigate(),[searchParams]=useSearchParams(),{conversations,characters,settings}=useStore(),[query,setQuery]=useState(""),[category,setCategory]=useState<FavoriteCategory>("all"),[conversationMessages,setConversationMessages]=useState<Message[]>([]),[cursor,setCursor]=useState<MessageCursor>(),[hasMore,setHasMore]=useState(false),[loadingOlder,setLoadingOlder]=useState(false);
 const conversation=conversations.find(item=>item.id===id),character=characters.find(item=>conversation?.type==="private"&&conversation.memberIds.includes(item.id)),favoritesOnly=searchParams.get("favorites")==="1";
 useEffect(()=>{let active=true;setConversationMessages([]);setCursor(undefined);setHasMore(false);if(!conversation?.id)return;void readConversationMessagePage(conversation.id).then(page=>{if(!active)return;setConversationMessages(page.items);setCursor(page.oldest);setHasMore(page.hasMore)});return()=>{active=false}},[conversation?.id]);
 const loadEarlier=async()=>{if(!conversation?.id||!cursor||!hasMore||loadingOlder)return;setLoadingOlder(true);try{const page=await readConversationMessagePage(conversation.id,cursor);setConversationMessages(current=>[...page.items,...current].filter((message,index,all)=>all.findIndex(row=>row.id===message.id)===index));setCursor(page.oldest);setHasMore(page.hasMore)}finally{setLoadingOlder(false)}};
 const results=useMemo<ChatSearchResult[]>(()=>{if(!conversation)return[];if(!favoritesOnly)return searchChatMessages(conversationMessages,query,characters,settings?.userName??"我",conversation);const needle=query.trim().toLocaleLowerCase();return conversationMessages.filter(message=>message.favoritedAt&&(category==="all"||messageCategory(message)===category)&&(!needle||searchableMessageText(message).toLocaleLowerCase().includes(needle))).sort((a,b)=>(b.favoritedAt??0)-(a.favoritedAt??0)).map(message=>({message,senderName:message.senderType==="user"?settings?.userName??"我":message.senderType==="system"?"系统":characters.find(item=>item.id===message.senderId)?.name??conversation.groupNpcs?.find(npc=>npc.id===message.senderId)?.name??"成员",summary:searchableMessageText(message).slice(0,180)})).slice(0,100)},[conversation,conversationMessages,query,characters,settings?.userName,favoritesOnly,category]);
 const groups=useMemo(()=>{const map=new Map<string,typeof results>();for(const result of results){const key=new Date(result.message.createdAt).toLocaleDateString("zh-CN",{year:"numeric",month:"long",day:"numeric"});map.set(key,[...(map.get(key)??[]),result])}return[...map.entries()]},[results]);
 if(!conversation)return <Navigate to="/messages/chats" replace/>;
 const empty=favoritesOnly&&!results.length&&!query.trim(),notFound=query.trim()&&!results.length,displayName=conversationDisplayName(conversation,character);
 if(favoritesOnly)return <div className="chat-search-page chat-favorites-page">
  <header><button aria-label="返回聊天设置" onClick={()=>nav(`/messages/${conversation.id}/settings`)}><ArrowLeft/></button><b>收藏</b><span/></header>
  <main><div className="favorite-search-head"><small>{displayName}</small><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索收藏内容"/>{query&&<button onClick={()=>setQuery("")}>清除</button>}</label><nav>{([{id:"all",label:"最近收藏"},{id:"chat",label:"聊天记录"},{id:"media",label:"图片与表情"},{id:"voice",label:"语音"}] as Array<{id:FavoriteCategory;label:string}>).map(item=><button key={item.id} className={category===item.id?"active":""} onClick={()=>setCategory(item.id)}>{item.label}</button>)}<span><ChevronDown/></span></nav></div>
   {empty?<div className="chat-search-empty favorite-empty"><Star/><h3>还没有收藏消息</h3><p>在与“{displayName}”的聊天中多选消息后点击“收藏”，内容就会独立保存在这里。</p></div>:notFound?<div className="chat-search-empty favorite-empty"><Search/><h3>没有找到相关收藏</h3><p>换一个关键词或收藏分类试试。</p></div>:<div className="favorite-message-list">{results.map(result=><button className={`favorite-message-card ${messageCategory(result.message)}`} key={result.message.id} onClick={()=>nav(`/messages/${conversation.id}?message=${result.message.id}`)}><div className="favorite-card-main"><span className="favorite-card-icon">{kindIcon(result.message)}</span><div><b>{favoriteTitle(result.message,result.summary)}</b><p>{result.summary}</p></div></div><footer><span>{result.senderName}</span><time>{new Date(result.message.createdAt).toLocaleDateString("zh-CN",{year:"numeric",month:"long",day:"numeric"})}</time></footer></button>)}</div>}
  {hasMore&&<button className="chat-search-more" disabled={loadingOlder} onClick={()=>void loadEarlier()}>{loadingOlder?"正在查找…":"继续查找更早记录"}</button>}</main>
 </div>;
 return <div className="chat-search-page"><header><button aria-label="返回聊天设置" onClick={()=>nav(`/messages/${conversation.id}/settings`)}><ArrowLeft/></button><b>搜索聊天记录</b><span/></header><main><div className="chat-search-title"><small>{displayName}</small><label><Search/><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索消息、引用、图片、语音、订单…"/>{query&&<button onClick={()=>setQuery("")}>清除</button>}</label></div>{notFound?<div className="chat-search-empty"><Search/><h3>没有找到相关内容</h3><p>换一个关键词试试。</p></div>:groups.map(([date,items])=><section key={date}><h3>{date}</h3>{items.map(result=><button key={result.message.id} onClick={()=>nav(`/messages/${conversation.id}?message=${result.message.id}`)}><span className="chat-search-kind">{kindIcon(result.message)}</span><span><b>{result.senderName}<time>{new Date(result.message.createdAt).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit",hour12:false})}</time></b><p>{result.summary}</p></span></button>)}</section>)}{hasMore&&<button className="chat-search-more" disabled={loadingOlder} onClick={()=>void loadEarlier()}>{loadingOlder?"正在查找…":"继续查找更早记录"}</button>}</main></div>;
}