import {useEffect,useLayoutEffect,useMemo,useRef,useState} from "react";
import {Outlet,useLocation,useNavigate} from "react-router-dom";
import {ArrowLeft,BatteryMedium,ChevronLeft,Wifi,X} from "lucide-react";
import {GlobalMusicMiniPlayer} from "../core/musicPlayer";
import {calculateMobileHomeLayout,isMobileHomeFullCanvasEnvironment} from "../core/mobileHomeLayout";
import {trustedMobileHomeViewportHeight} from "../core/mobileHomeGeometry";
import {calculateMobileHomeFooterRecovery} from "../core/mobileHomeFooterRecovery";
import {cssViewportVariablesOf,readMobileViewportSnapshot,type MobileViewportSnapshot} from "../core/mobileViewport";

export function PhoneShell(){
  const nav=useNavigate(),loc=useLocation();
  const [time,setTime]=useState("");
  const [viewportSnapshot,setViewportSnapshot]=useState<MobileViewportSnapshot>(()=>{
    if(typeof window==="undefined")return readMobileViewportSnapshot({innerWidth:390,innerHeight:844,documentClientWidth:390,documentClientHeight:844});
    return readMobileViewportSnapshot({innerWidth:window.innerWidth,innerHeight:window.innerHeight,documentClientWidth:document.documentElement.clientWidth,documentClientHeight:document.documentElement.clientHeight,visualWidth:window.visualViewport?.width,visualHeight:window.visualViewport?.height,visualOffsetTop:window.visualViewport?.offsetTop});
  });
  const [nativeViewport,setNativeViewport]=useState(()=>typeof window!=="undefined"&&(((navigator.maxTouchPoints??0)>0||window.matchMedia("(hover: none) and (pointer: coarse)").matches)||Math.min(window.innerWidth,document.documentElement.clientWidth||window.innerWidth)<=600));
  const [homeRecovery,setHomeRecovery]=useState(false);
  const homeLayoutLatch=useRef(false),homeRecoveryLatch=useRef(false);
  useEffect(()=>{
    const root=document.documentElement,viewport=window.visualViewport,virtualKeyboard=(navigator as Navigator&{virtualKeyboard?:{boundingRect?:{height?:number};addEventListener?:(type:string,listener:EventListener)=>void;removeEventListener?:(type:string,listener:EventListener)=>void}}).virtualKeyboard;
    const safeAreaProbe=document.createElement("div");safeAreaProbe.setAttribute("aria-hidden","true");safeAreaProbe.style.cssText="position:fixed;visibility:hidden;pointer-events:none;padding-top:env(safe-area-inset-top,0px);padding-bottom:env(safe-area-inset-bottom,0px)";document.body.appendChild(safeAreaProbe);
    let stableLayoutWidth=0,stableLayoutHeight=0;
    const update=()=>{
      const probeStyle=getComputedStyle(safeAreaProbe);
      const input={innerWidth:window.innerWidth,innerHeight:window.innerHeight,documentClientWidth:document.documentElement.clientWidth,documentClientHeight:document.documentElement.clientHeight,visualWidth:viewport?.width,visualHeight:viewport?.height,visualOffsetTop:viewport?.offsetTop,virtualKeyboardInset:virtualKeyboard?.boundingRect?.height,safeAreaTop:parseFloat(probeStyle.paddingTop)||0,safeAreaBottom:parseFloat(probeStyle.paddingBottom)||0,stableLayoutWidth:stableLayoutWidth||undefined,stableLayoutHeight:stableLayoutHeight||undefined};
      const raw=readMobileViewportSnapshot(input);if(raw.keyboardMode==="none"){stableLayoutWidth=raw.layoutWidth;stableLayoutHeight=raw.layoutHeight;}
      const snapshot=readMobileViewportSnapshot({...input,stableLayoutWidth:stableLayoutWidth||undefined,stableLayoutHeight:stableLayoutHeight||undefined});
      Object.entries(cssViewportVariablesOf(snapshot)).forEach(([name,value])=>root.style.setProperty(name,value));root.dataset.chachaKeyboardMode=snapshot.keyboardMode==="viewport-shrink"?"resize":snapshot.keyboardMode;setViewportSnapshot(snapshot);
      const narrow=snapshot.layoutWidth<=600;setNativeViewport((navigator.maxTouchPoints??0)>0||window.matchMedia("(hover: none) and (pointer: coarse)").matches||narrow);
    };
    const clear=()=>{root.dataset.chachaKeyboardMode="none";update()};const onVisibility=()=>document.visibilityState==="visible"?update():clear();update();
    viewport?.addEventListener("resize",update);viewport?.addEventListener("scroll",update);virtualKeyboard?.addEventListener?.("geometrychange",update);window.addEventListener("resize",update);window.addEventListener("orientationchange",update);window.addEventListener("pageshow",update);window.addEventListener("pagehide",clear);document.addEventListener("visibilitychange",onVisibility);
    return()=>{viewport?.removeEventListener("resize",update);viewport?.removeEventListener("scroll",update);virtualKeyboard?.removeEventListener?.("geometrychange",update);window.removeEventListener("resize",update);window.removeEventListener("orientationchange",update);window.removeEventListener("pageshow",update);window.removeEventListener("pagehide",clear);document.removeEventListener("visibilitychange",onVisibility);delete root.dataset.chachaKeyboardMode;safeAreaProbe.remove()};
  },[]);
  const displayModeStandalone=typeof window!=="undefined"&&window.matchMedia("(display-mode: standalone)").matches,displayModeFullscreen=typeof window!=="undefined"&&window.matchMedia("(display-mode: fullscreen)").matches,displayModeMinimalUi=typeof window!=="undefined"&&window.matchMedia("(display-mode: minimal-ui)").matches,navigatorStandalone=typeof window!=="undefined"&&(window.navigator as Navigator&{standalone?:boolean}).standalone===true,androidAppReferrer=typeof document!=="undefined"&&document.referrer.startsWith("android-app://"),standalone=displayModeStandalone||displayModeFullscreen||displayModeMinimalUi||navigatorStandalone||androidAppReferrer;
  useLayoutEffect(()=>{document.documentElement.setAttribute("data-chacha-standalone",standalone?"true":"false");return()=>document.documentElement.removeAttribute("data-chacha-standalone")},[standalone]);
  const home=loc.pathname==="/";
  const homeLayout=useMemo(()=>calculateMobileHomeLayout({viewportWidth:viewportSnapshot.layoutWidth,viewportHeight:viewportSnapshot.layoutHeight,safeAreaTop:viewportSnapshot.safeAreaTop,safeAreaBottom:viewportSnapshot.safeAreaBottom}),[viewportSnapshot]);
  const touchCapable=typeof window!=="undefined"&&((navigator.maxTouchPoints??0)>0||window.matchMedia("(hover: none) and (pointer: coarse)").matches),screenWidth=typeof screen!=="undefined"?screen.width:0,screenHeight=typeof screen!=="undefined"?screen.height:0,screenAvailHeight=typeof screen!=="undefined"?screen.availHeight:0;
  const keyboard=viewportSnapshot.keyboardInset,keyboardOpen=viewportSnapshot.keyboardMode!=="none",activeElement=typeof document!=="undefined"?document.activeElement as HTMLElement|null:null,editableFocused=Boolean(activeElement&&(activeElement.matches("input, textarea, select")||activeElement.isContentEditable)),homeKeyboardOpen=keyboardOpen&&editableFocused;
  const homeEnvironmentMatch=isMobileHomeFullCanvasEnvironment({routeIsHome:home,viewportWidth:viewportSnapshot.layoutWidth,viewportHeight:viewportSnapshot.layoutHeight,screenWidth,screenHeight,screenAvailHeight,touchCapable,portrait:viewportSnapshot.layoutHeight>viewportSnapshot.layoutWidth,keyboardOpen:homeKeyboardOpen,displayModeStandalone,displayModeFullscreen,displayModeMinimalUi,navigatorStandalone,androidAppReferrer});
  if(homeEnvironmentMatch)homeLayoutLatch.current=true;
  const pwaHomeLayout=home&&nativeViewport&&homeLayout.enabled&&homeLayoutLatch.current;
  const trustedRecoveryHeight=trustedMobileHomeViewportHeight({visualHeight:viewportSnapshot.visualHeight,visualOffsetTop:viewportSnapshot.visualOffsetTop,innerHeight:window.innerHeight,clientHeight:document.documentElement.clientHeight||window.innerHeight,screenHeight,screenAvailHeight});
  const recoveryLayout=useMemo(()=>calculateMobileHomeFooterRecovery({viewportWidth:viewportSnapshot.layoutWidth,viewportHeight:trustedRecoveryHeight,safeAreaTop:viewportSnapshot.safeAreaTop,safeAreaBottom:viewportSnapshot.safeAreaBottom}),[viewportSnapshot.layoutWidth,viewportSnapshot.safeAreaTop,viewportSnapshot.safeAreaBottom,trustedRecoveryHeight]);
  const recoveryCandidate=home&&nativeViewport&&touchCapable&&viewportSnapshot.layoutWidth<=600&&viewportSnapshot.layoutHeight>viewportSnapshot.layoutWidth&&!homeKeyboardOpen&&(homeEnvironmentMatch||homeLayoutLatch.current);
  useEffect(()=>{const onRecovery=(event:Event)=>{const detail=(event as CustomEvent<{recover?:boolean}>).detail;if(!detail?.recover||!recoveryCandidate||homeRecoveryLatch.current)return;homeRecoveryLatch.current=true;setHomeRecovery(true)};window.addEventListener("chacha:home-geometry-recovery",onRecovery);return()=>window.removeEventListener("chacha:home-geometry-recovery",onRecovery)},[recoveryCandidate]);
  const pwaHomeRecovery=home&&homeRecoveryLatch.current&&homeRecovery,appearanceRoot=loc.pathname.startsWith("/appearance"),characterRoot=loc.pathname.startsWith("/characters"),settingsRoot=loc.pathname==="/settings"||loc.pathname.startsWith("/settings/"),meetRoot=loc.pathname.startsWith("/meet"),phoneCheckRoot=loc.pathname.startsWith("/phone-check"),mallRoot=loc.pathname.startsWith("/mall"),musicRoot=loc.pathname.startsWith("/music"),coupleIslandRoot=loc.pathname.startsWith("/couple-island"),forumRoot=loc.pathname.startsWith("/forum"),memoryRoot=loc.pathname.startsWith("/memories"),loreRoot=loc.pathname.startsWith("/lore"),messageFlowRoot=/^\/messages\/(?:contacts\/(?:add|requests)|group\/new|[^/]+\/members\/add)$/.test(loc.pathname),stickerSettingsRoot=loc.pathname==="/settings/stickers",chatSettingsRoot=/^\/messages\/[^/]+\/settings$/.test(loc.pathname),chatChildRoot=/^\/messages\/[^/]+\/(?:settings|search|inner-voice\/(?:character|npc)\/[^/]+)$/.test(loc.pathname),chatRoomRoot=/^\/messages\/[^/]+$/.test(loc.pathname),socialRoot=["/messages/chats","/messages/feed","/messages/contacts","/messages/me"].includes(loc.pathname),nativeTopbarRoot=meetRoot||mallRoot||forumRoot||loreRoot||musicRoot||coupleIslandRoot||stickerSettingsRoot||chatSettingsRoot||messageFlowRoot;
  useLayoutEffect(()=>{const root=document.documentElement;if(pwaHomeRecovery)root.dataset.chachaHomeRecovery="true";else delete root.dataset.chachaHomeRecovery;return()=>{delete root.dataset.chachaHomeRecovery}},[pwaHomeRecovery]);
  const homeStyleLayout=pwaHomeRecovery?recoveryLayout:(pwaHomeLayout?homeLayout:null);
  const shellStyle={...cssViewportVariablesOf(viewportSnapshot),...(homeStyleLayout?{"--pwa-home-desktop-height":`${homeStyleLayout.desktopHeight}px`,"--pwa-home-row-1":`${homeStyleLayout.rowHeights[0]}px`,"--pwa-home-row-2":`${homeStyleLayout.rowHeights[1]}px`,"--pwa-home-row-3":`${homeStyleLayout.rowHeights[2]}px`,"--pwa-home-row-4":`${homeStyleLayout.rowHeights[3]}px`,"--pwa-home-row-5":`${homeStyleLayout.rowHeights[4]}px`,"--pwa-home-row-6":`${homeStyleLayout.rowHeights[5]}px`,"--pwa-home-gap-1":`${homeStyleLayout.rowGaps[0]}px`,"--pwa-home-gap-2":`${homeStyleLayout.rowGaps[1]}px`,"--pwa-home-gap-3":`${homeStyleLayout.rowGaps[2]}px`,"--pwa-home-gap-4":`${homeStyleLayout.rowGaps[3]}px`,"--pwa-home-gap-5":`${homeStyleLayout.rowGaps[4]}px`,"--pwa-home-row-gap":`${pwaHomeRecovery?recoveryLayout.rowGaps[0]:homeLayout.rowGap}px`,"--pwa-home-top-padding":`${homeStyleLayout.topPadding}px`,"--pwa-home-bottom-padding":`${homeStyleLayout.bottomPadding}px`,"--pwa-home-footer-height":`${homeStyleLayout.footerHeight}px`,"--pwa-home-content-to-dots-gap":`${homeStyleLayout.contentToDotsGap}px`,"--pwa-home-footer-gap":`${homeStyleLayout.dotsToDockGap}px`,"--pwa-home-dock-height":`${homeStyleLayout.dockHeight}px`,"--pwa-home-hero-height":`${homeStyleLayout.heroHeight}px`,"--pwa-home-hero-thumb-size":`${homeStyleLayout.heroThumbSize}px`,...(pwaHomeRecovery?{"--pwa-home-recovery-height":`${recoveryLayout.viewportHeight}px`}:null)}:null)} as React.CSSProperties;
  return <main className="stage"><section className={`phone ${keyboard?"keyboard-open ":""}${standalone?"standalone-mode ":""}${nativeViewport?"native-mobile-viewport ":""}${pwaHomeLayout?"pwa-home-layout-v3 ":""}${recoveryCandidate?"pwa-home-recovery-candidate ":""}${pwaHomeRecovery?"pwa-home-layout-v5-recovery ":""}${stickerSettingsRoot?"sticker-settings-route ":""}${chatSettingsRoot?"chat-settings-route ":""}${messageFlowRoot?"message-flow-route ":""}${forumRoot?"forum-route ":""}${nativeTopbarRoot?"native-topbar-route":""}`} style={shellStyle}><div className="wallpaper"/><header className="status"><b>{time}</b><span className="signals"><Wifi size={15}/><BatteryMedium size={18}/></span></header><div className="screen"><Outlet/></div>{!musicRoot&&<GlobalMusicMiniPlayer/>}{!home&&!socialRoot&&!chatChildRoot&&!appearanceRoot&&!characterRoot&&!settingsRoot&&!meetRoot&&!phoneCheckRoot&&!mallRoot&&!musicRoot&&!coupleIslandRoot&&!forumRoot&&!memoryRoot&&!loreRoot&&!messageFlowRoot&&<button className="back" onClick={()=>chatRoomRoot?nav("/messages/chats"):nav(-1)} aria-label="返回"><ArrowLeft/></button>}</section></main>}export const APP_TOPBAR_CONTENT_HEIGHT=58;
export function AppTopBar({title,onBack,backLabel="返回",actions,className="",titleClassName=""}:{title:string;onBack:()=>void;backLabel?:string;actions?:React.ReactNode;className?:string;titleClassName?:string}){return <header className={`app-topbar ${className}`.trim()} style={{"--app-topbar-content-height":`${APP_TOPBAR_CONTENT_HEIGHT}px`} as React.CSSProperties}><button type="button" className="app-topbar-back" aria-label={backLabel} onClick={onBack}><ChevronLeft/></button><h1 className={`app-topbar-title ${titleClassName}`.trim()}>{title}</h1><div className="app-topbar-actions">{actions}</div></header>}
export function AppHeader({title,subtitle,action}:{title:string;subtitle?:string;action?:React.ReactNode}){return <header className="app-header"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{action}</header>}
export function Avatar({text,src,size="md"}:{text:string;src?:string;size?:"sm"|"md"|"lg"}){const [broken,setBroken]=useState(false);useEffect(()=>setBroken(false),[src]);return src&&!broken?<img className={`avatar ${size}`} src={src} alt={`${text}头像`} loading="lazy" onError={()=>setBroken(true)}/>:<span className={`avatar avatar-fallback ${size}`} aria-label={`${text}头像占位`}>{text.slice(0,1)}</span>}
export function Empty({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="empty">{icon}<h3>{title}</h3><p>{text}</p></div>}
export function SheetHeader({title,onClose}:{title:string;onClose:()=>void}){return <div className="sheet-head"><h2>{title}</h2><button type="button" aria-label="关闭" onClick={onClose}><X/></button></div>}
export function Modal({children,onClose}:{children:React.ReactNode;onClose:()=>void}){return <div className="modal-shade" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal">{children}</div></div>}
