import {db,getAppSettings} from "./db";
import {backgroundActivitySettingsOf} from "./notificationSettings";
import {now,SCHEMA_VERSION,uid,type BackgroundTask,type BackgroundTaskType} from "./types";
import {dataLifecycleMutationActive} from "./dataLifecycle";

export const BACKGROUND_TASK_LEASE_MS=5*60*1000;
async function requestBackgroundSync(){if(typeof navigator==="undefined"||!("serviceWorker" in navigator))return;try{const background=backgroundActivitySettingsOf(await getAppSettings());if(!background.enabled||!background.modes?.length)return;const registration=await navigator.serviceWorker.ready;if("sync" in registration)await (registration as ServiceWorkerRegistration&{sync:{register(tag:string):Promise<void>}}).sync.register("chacha-background")}catch{}}
export type BackgroundTaskInput={type:BackgroundTaskType;entityId:string;characterId?:string;conversationId?:string;scheduledAt?:number;nextAttemptAt?:number;eventId:string;payload?:unknown};

export async function enqueueBackgroundTask(input:BackgroundTaskInput){const existing=await db.backgroundTasks.where("eventId").equals(input.eventId).first();if(existing)return existing;const t=now(),task:BackgroundTask={id:uid(),schemaVersion:SCHEMA_VERSION,createdAt:t,updatedAt:t,type:input.type,entityId:input.entityId,characterId:input.characterId,conversationId:input.conversationId,state:"pending",scheduledAt:input.scheduledAt??t,nextAttemptAt:input.nextAttemptAt??input.scheduledAt??t,attempts:0,eventId:input.eventId,payload:input.payload??{}};await db.backgroundTasks.add(task);void requestBackgroundSync();return task}
export async function backgroundTaskByEvent(eventId:string){return db.backgroundTasks.where("eventId").equals(eventId).first()}
export async function recoverExpiredBackgroundTasks(at=now()){if(dataLifecycleMutationActive())return;const rows=await db.backgroundTasks.where("state").equals("running").toArray();for(const task of rows)if((task.leaseExpiresAt??0)<=at){const {leaseExpiresAt:_,...rest}=task;await db.backgroundTasks.put({...rest,state:"pending",nextAttemptAt:Math.min(task.nextAttemptAt,at),updatedAt:at})}}
export async function claimDueBackgroundTasks(limit=12,at=now(),types?:BackgroundTaskType[]){if(dataLifecycleMutationActive())return [];await recoverExpiredBackgroundTasks(at);if(dataLifecycleMutationActive())return [];const rows=await db.backgroundTasks.where("nextAttemptAt").belowOrEqual(at).filter(task=>(task.state==="pending"||task.state==="failed")&&task.scheduledAt<=at&&(!types||types.includes(task.type))).sortBy("nextAttemptAt"),claimed:BackgroundTask[]=[];for(const task of rows.slice(0,limit)){const changed=await db.backgroundTasks.update(task.id,{state:"running",attempts:task.attempts+1,leaseExpiresAt:at+BACKGROUND_TASK_LEASE_MS,updatedAt:at});if(changed)claimed.push({...task,state:"running",attempts:task.attempts+1,leaseExpiresAt:at+BACKGROUND_TASK_LEASE_MS,updatedAt:at})}return claimed}
export async function completeBackgroundTask(taskId:string){const task=await db.backgroundTasks.get(taskId);if(!task)return;const {leaseExpiresAt:_,lastError:__,...rest}=task;await db.backgroundTasks.put({...rest,state:"completed",updatedAt:now()})}
export async function failBackgroundTask(taskId:string,error:unknown,retryMs=60_000){const task=await db.backgroundTasks.get(taskId);if(!task)return;const {leaseExpiresAt:_,...rest}=task;await db.backgroundTasks.put({...rest,state:"failed",lastError:error instanceof Error?error.message:String(error),nextAttemptAt:now()+Math.min(60*60*1000,retryMs*Math.max(1,2**Math.min(task.attempts,6))),updatedAt:now()})}
export async function cancelBackgroundTaskByEvent(eventId:string){const task=await backgroundTaskByEvent(eventId);if(task&&task.state!=="completed")await completeBackgroundTask(task.id)}
export async function pruneBackgroundTasks(before=now()-7*24*60*60*1000){await db.backgroundTasks.where("updatedAt").below(before).filter(task=>task.state==="completed").delete()}