import type {AppSettings,Character,ChatScene,Conversation,GroupNpc,LoreBook,MediaAsset,Memory,Message,ProviderSettings,RegenerationReason} from "./types";
import {messageInteractionContext} from "./messageInteractions";
import {localTimeContext} from "./localTime";
import {selectMemories} from "./memory";
import {chatSettingsOf,coreSettingOf,languageStyleInstruction,personaOf,relationshipContextOf} from "./character";
import {userPersonaContext} from "./userPersona";
import {compiledLoreContext,performanceProfileContext,strongRoleplayInstruction} from "./personaEngine";
import {evaluateLore,groupLoreByInsertion,isLoreBookMounted,loreEntriesBlock,matchLore,scopeMatches} from "./lore";
import {chatPresenceInstruction,type ChatPresenceContext} from "./chatPresence";
import {INTERNAL_LORE_BUDGET_TOKENS} from "./tokenBudget";
export {matchLore,scopeMatches} from "./lore";

export type ChatItem={role:"system"|"user"|"assistant";content:string;imageUrl?:string;imageUrls?:string[]};
export function chooseSpeaker(conversation:Conversation,messages:Message[]){const ids=messages.filter(message=>message.conversationId===conversation.id&&message.senderType==="character").map(message=>message.senderId),last=ids.at(-1);return conversation.memberIds.find(id=>id!==last)??conversation.memberIds[0]}
export function conversationLoreBooks(character:Character,conversation:Conversation,books:LoreBook[]){return books.filter(book=>isLoreBookMounted(book,character.id,conversation.id,character,conversation))}
function messageCommerceContext(message:Message){const textImage=message.attachments?.find(item=>item.type==="text-image"),sticker=message.attachments?.find(item=>item.type==="sticker"),attachment=message.attachments?.find(item=>["commerce","transfer","red-packet","poll","music-invitation","music-event","music-search-candidates","music-control-proposal","music-session-summary","couple-island-invitation"].includes(item.type));let content=sticker?.type==="sticker"?`[${message.senderType==="user"?"用户":"角色"}发送了表情包；含义：${sticker.description||sticker.name}]`:message.content;if(textImage?.type==="text-image")content+=`${content?"\n":""}[文字图片：${textImage.description}]`;if(attachment?.type==="transfer")content+=`\n转账方向：${attachment.direction==="character-to-user"?"角色转给用户":"用户转给角色"}；金额 ¥${(attachment.amountCents/100).toFixed(2)}；状态 ${attachment.state}`;else if(attachment?.type==="commerce")content+=`\n订单：${attachment.itemNames.join("、")}；接收人：${attachment.recipientName}；金额 ¥${(attachment.amountCents/100).toFixed(2)}；状态 ${attachment.status}`;else if(attachment?.type==="red-packet")content+=`\n红包总额 ¥${(attachment.totalAmountCents/100).toFixed(2)}；${attachment.claims.map(claim=>`${claim.participantName??claim.characterName??"成员"}领取¥${(claim.amountCents/100).toFixed(2)}`).join("；")}`;else if(attachment?.type==="poll")content+=`\n投票：${attachment.question}；选项 ${attachment.options.map(option=>option.text).join("、")}；已有投票 ${attachment.votes.map(vote=>`${vote.voterName}=${vote.optionIds.map((id:string)=>attachment.options.find(option=>option.id===id)?.text).filter(Boolean).join("、")}`).join("；")}`;else if(attachment?.type==="music-invitation")content+=`\n一起听邀请状态：${attachment.state}${attachment.trackId?`；歌曲ID ${attachment.trackId}`:""}`;else if(attachment?.type==="music-event")content+=`\n一起听事件：${attachment.eventType}${attachment.trackId?`；歌曲ID ${attachment.trackId}`:""}`;else if(attachment?.type==="music-search-candidates")content+=`\n角色DJ搜索候选：${attachment.query}；状态 ${attachment.state}；候选ID ${attachment.trackIds.join("、")}`;else if(attachment?.type==="music-control-proposal")content+=`\n角色DJ控制建议：${attachment.control}；状态 ${attachment.state}；原因：${attachment.reason}`;else if(attachment?.type==="music-session-summary")content+=`\n一起听小结：${attachment.trackIds.length} 首；约 ${Math.max(1,Math.round(attachment.listenedMs/60000))} 分钟${attachment.closingNote?`；结束语：${attachment.closingNote}`:""}`;else if(attachment?.type==="couple-island-invitation")content+=`\n茶侣岛${attachment.cardRole==="response"||message.senderType==="character"?"角色回应":"邀请"}状态：${attachment.state}${attachment.reason?`；原因：${attachment.reason}`:""}`;return messageInteractionContext(message,content)}
const reasonLabels:Record<RegenerationReason,string>={ooc:"角色 OOC","context-conflict":"与上下文不符","memory-conflict":"角色失忆","lore-conflict":"世界书理解错误","speech-style":"说话方式不符合人设","model-leak":"暴露模型或系统信息",other:"其他"};
export function buildContext(input:{character:Character;conversation:Conversation;messages:Message[];loreBooks:LoreBook[];memories:Memory[];userText:string;settings:Partial<Pick<AppSettings,"sensitiveContent"|"userName"|"userBio"|"userPersona">>;provider:ProviderSettings;characters?:Character[];groupNpcs?:GroupNpc[];mediaAssets?:MediaAsset[];forumContext?:string;scene?:ChatScene;regenerationReasons?:RegenerationReason[];regenerationInstruction?:string;forceAllLore?:boolean;presence?:ChatPresenceContext;crossModeContinuity?:string;timeAt?:Date}):ChatItem[]{
 const {character,conversation,userText}=input,chat=chatSettingsOf(character),recent=input.messages.filter(message=>message.conversationId===conversation.id&&message.status==="complete").slice(-chat.contextLimit),texts=[...recent.map(message=>messageCommerceContext(message)),userText,input.regenerationInstruction??""],seed=`${recent.at(-1)?.id??""}:${userText}:${input.regenerationInstruction??""}`,books=conversationLoreBooks(character,conversation,input.loreBooks),forceAllLore=input.forceAllLore||input.regenerationReasons?.includes("lore-conflict"),lore=evaluateLore({books,texts,characterId:character.id,conversationId:conversation.id,character,conversation,seed,forceAll:forceAllLore,budget:Math.floor(INTERNAL_LORE_BUDGET_TOKENS*3.2)}).filter(entry=>entry.injected),loreGroups=groupLoreByInsertion(lore),memoryLimit=input.regenerationReasons?.includes("memory-conflict")?(conversation.type==="group"?8:20):(conversation.type==="group"?4:10),memory=selectMemories(input.memories,character.id,conversation.id,memoryLimit,userText,character.memoryExtractionSettings?.enabled??true),time=localTimeContext({enabled:character.proactive.timeAware,at:input.timeAt}),scene=input.scene??(conversation.type==="group"?"group-chat":"private-chat"),isNpc=input.groupNpcs?.some(npc=>npc.id===character.id)??false,rawLoreBookIds=new Set(lore.map(entry=>entry.bookId)),compiledLore=compiledLoreContext(books.filter(book=>!rawLoreBookIds.has(book.id))).slice(0,24000),regeneration=[input.regenerationReasons?.length?`本次重新回复需要修复：${input.regenerationReasons.map(reason=>reasonLabels[reason]).join("、")}。`:"",input.regenerationInstruction?.trim()?`本次一次性导演要求：${input.regenerationInstruction.trim()}。它只影响本次回复，低于角色核心设定、完整人设和世界书硬规则，不得保存为角色事实。`:""].filter(Boolean).join("\n"),system=[
  strongRoleplayInstruction(scene,isNpc),
  chatPresenceInstruction(input.presence??{mode:"remote",evidence:"default"}),
  input.crossModeContinuity??"",
  loreEntriesBlock(loreGroups["base-rules"]),
  `当前演绎角色：${character.name}\n核心设定：${coreSettingOf(character)}\n人物设定：${personaOf(character)}\n${languageStyleInstruction(chat.language)}`,
  performanceProfileContext(character),
  loreEntriesBlock(loreGroups["after-character"]),
  conversation.type==="group"?`你正在群聊“${conversation.title}”中发言。只扮演${character.name}，不要代替其他成员发言。${conversation.chatSettings?.userInGroup===false?"用户不属于群成员；标记为幕后指导的内容只是导演指令，不要在群内提及用户或指令来源。":"用户是群聊成员。"}`:"",
  conversation.type!=="group"||conversation.chatSettings?.userInGroup!==false?userPersonaContext(input.settings):"",
  time,
  compiledLore,
  isNpc?"":relationshipContextOf(character),
  memory.length?`海马体记忆（自然使用，不得提及记忆系统或评分）：\n${memory.map(item=>`- ${item.title?`${item.title}：`:""}${item.content}${item.meaning?`（意义：${item.meaning}）`:""}`).join("\n")}`:"",
  loreEntriesBlock(loreGroups["after-memory"]),
  input.forumContext?`论坛互通内容：\n${input.forumContext}`:"",
  regeneration,
 ].filter(Boolean).join("\n\n"),history=recent.map<ChatItem>(message=>{if(message.kind==="director")return{role:"system",content:`[仅用户可见的幕后指导] ${message.content}`};if(message.senderType==="system")return{role:"system",content:messageCommerceContext(message)};const media=message.attachments?.find(attachment=>attachment.type==="image"||attachment.type==="sticker"),assetId=media&&"assetId" in media?media.assetId:undefined,asset=assetId?input.mediaAssets?.find(item=>item.id===assetId):undefined,imageUrl=media?.type==="image"&&media.visionMode==="description"?undefined:(asset?.data||(media&&"url" in media?media.url:undefined)),name=message.senderType==="user"?(input.settings.userName?.trim()||"我"):input.characters?.find(item=>item.id===message.senderId)?.name??input.groupNpcs?.find(item=>item.id===message.senderId)?.name??"成员",content=conversation.type==="group"?`${name}：${messageCommerceContext(message)}`:messageCommerceContext(message);return{role:message.senderType==="user"?"user":"assistant",content,imageUrl}});return[{role:"system",content:system},...(loreGroups["before-history"].length?[{role:"system" as const,content:loreEntriesBlock(loreGroups["before-history"])}]:[]),...history,...(loreGroups["before-user"].length?[{role:"system" as const,content:loreEntriesBlock(loreGroups["before-user"])}]:[]),{role:"user",content:userText}]
}





