import {beforeEach,describe,expect,it,vi} from "vitest";
import {db} from "./db";
import {backgroundTaskReferences,deleteBackgroundTasksReferencing,findOrphanRecords,repairOrphanRecords,resetUserData} from "./dataLifecycle";
import {defaultAppSettings,type BackgroundTask} from "./types";
import {readPersonaDraft,writePersonaDraft} from "./userPersonaDraft";

const task=(overrides:Partial<BackgroundTask>={}):BackgroundTask=>({id:"task",schemaVersion:1,createdAt:1,updatedAt:1,type:"proactive-message",entityId:"entity",characterId:"character",conversationId:"conversation",state:"pending",scheduledAt:1,nextAttemptAt:1,attempts:0,eventId:"event",payload:{messageId:"message"},...overrides});

describe("data lifecycle consistency",()=>{
 beforeEach(async()=>{await db.delete();await db.open();localStorage.clear();vi.restoreAllMocks()});
 it("finds task references in direct fields and known payload ids",()=>{expect(backgroundTaskReferences(task(),["character"])).toBe(true);expect(backgroundTaskReferences(task({characterId:undefined,payload:{sourceMessageId:"message"}}),["message"])).toBe(true);expect(backgroundTaskReferences(task({characterId:undefined,conversationId:undefined,payload:{note:"message"}}),["message"])).toBe(false)});
 it("deletes every background task referencing a removed entity",async()=>{await db.backgroundTasks.bulkAdd([task(),task({id:"other",eventId:"other",characterId:"other-character",conversationId:"other-conversation",payload:{}})]);expect(await deleteBackgroundTasksReferencing(["character","conversation","message"])).toBe(1);expect(await db.backgroundTasks.toArray()).toMatchObject([{id:"other"}])});
 it("reports user-visible orphans and only repairs safe derived records",async()=>{await db.messages.add({id:"orphan-message",conversationId:"missing",schemaVersion:1,createdAt:1,updatedAt:1,senderType:"user",senderId:"user",kind:"text",content:"keep me",status:"complete"} as any);await db.backgroundTasks.add(task());await db.memoryVectors.add({memoryId:"missing-memory",characterId:"missing-character",model:"x",dimensions:1,values:[1],contentHash:"x",updatedAt:1} as any);await db.musicEvents.add({id:"music-event",schemaVersion:1,createdAt:1,updatedAt:1,sessionId:"missing-session",conversationId:"missing",characterId:"missing-character",type:"play",actor:"system"});const audit=await findOrphanRecords();expect(audit.counts).toMatchObject({"background-task":1,message:1,"memory-vector":1,"music-event":1});const result=await repairOrphanRecords(audit);expect(result.deleted).toBe(3);expect(await db.messages.get("orphan-message")).toBeTruthy();expect(await db.backgroundTasks.count()).toBe(0);expect(await db.memoryVectors.count()).toBe(0);expect(await db.musicEvents.count()).toBe(0)});
 it("factory reset clears every Mira table, IndexedDB persona draft and secrets while keeping activation storage separate",async()=>{await db.characters.add({id:"character",schemaVersion:1,createdAt:1,updatedAt:1,name:"角色"} as any);await db.musicFiles.add({id:"file",schemaVersion:1,createdAt:1,updatedAt:1,blob:new Blob(["x"]),mimeType:"audio/mpeg",sizeBytes:1} as any);await db.backgroundTasks.add(task());await db.settings.bulkPut([{key:"provider",value:{apiKey:"secret"}},{key:"app",value:{...defaultAppSettings,onboarded:true}}]);localStorage.setItem("chacha-user-persona-draft-v1","draft");const result=await resetUserData();expect(result.activationPreserved).toBe(true);expect(await db.characters.count()).toBe(0);expect(await db.musicFiles.count()).toBe(0);expect(await db.backgroundTasks.count()).toBe(0);expect(await db.settings.get("provider")).toBeUndefined();expect((await db.settings.get("app"))?.value).toMatchObject({onboarded:false});expect(localStorage.getItem("chacha-user-persona-draft-v1")).toBeNull();await writePersonaDraft({name:"?",nickname:"",bio:"bio",persona:"persona",avatar:"",updatedAt:1});expect(await readPersonaDraft()).toBeTruthy();await resetUserData();expect(await readPersonaDraft()).toBeUndefined()});
});
