import Dexie,{type EntityTable} from "dexie";
import {defaultProvider} from "./types";
import type {Character,Conversation,Message,Preset,LoreBook,Memory,FeedPost,ProviderSettings,AppSettings,MemoryExtractionBatch,ImageAsset,AppearanceSettings,MediaAsset,StickerPack,SpeechSettings,ImageGenerationSettings,ModelServiceSettings,MeetSession,MallCatalogItem,MallCartItem,MallOrder,WalletTransaction,MallWalletSettings,ForumServer,ForumChannel,ForumPost,BackgroundTask,MemoryVector,CharacterPhoneState,MusicTrack,MusicFile,MusicPlaylist,ListeningSession,MusicEvent,CoupleIsland,CoupleIslandObject,CoupleIslandEntry,CoupleIslandEvent} from "./types";
import {defaultSpeechSettings,defaultModelServiceSettings,defaultImageGenerationSettings} from "./types";
export interface SettingRecord{key:string;value:unknown}
export interface MemoryExtractionCursor{key:string;lastSourceId?:string;updatedAt:number}
const islandStores={coupleIslands:"id,characterId,conversationId,status,lastActivityAt,updatedAt",coupleIslandObjects:"id,islandId,kind,zone,location,updatedAt",coupleIslandEntries:"id,islandId,kind,state,createdAt,updatedAt",coupleIslandEvents:"id,islandId,type,sourceId,createdAt"};
const coreStores={characters:"id,updatedAt,lastActiveAt",conversations:"id,type,lastActivityAt,*memberIds",messages:"id,conversationId,createdAt,senderId,kind,origin,[conversationId+createdAt+id]",presets:"id,updatedAt",loreBooks:"id,updatedAt",memories:"id,characterId,conversationId,kind,importance",feedPosts:"id,authorId,createdAt",memoryExtractionBatches:"id,status,characterId,conversationId,source,createdAt",memoryExtractionCursors:"key,updatedAt",imageAssets:"id,purpose,updatedAt",mediaAssets:"id,purpose,updatedAt",stickerPacks:"id,order,updatedAt",meetSessions:"id,status,conversationId,lastActivityAt,*participantIds",mallCatalogItems:"id,kind,searchId,query,createdAt,merchantId",mallCartItems:"id,cartKind,catalogItemId,merchantId,createdAt",mallOrders:"id,kind,status,recipientId,createdAt",walletTransactions:"id,kind,state,orderId,messageId,createdAt",forumServers:"id,order,updatedAt",forumChannels:"id,serverId,order,kind",forumPosts:"id,channelId,lastActivityAt,authorId,*tags",backgroundTasks:"id,type,state,nextAttemptAt,scheduledAt,eventId,characterId,conversationId,updatedAt",memoryVectors:"memoryId,characterId,model,contentHash,updatedAt",musicTracks:"id,source,externalId,updatedAt,importedAt",musicFiles:"id,updatedAt",musicPlaylists:"id,source,externalId,updatedAt,syncedAt",listeningSessions:"id,state,conversationId,characterId,updatedAt",musicEvents:"id,sessionId,conversationId,characterId,type,createdAt",settings:"key"};
export class MiraDB extends Dexie{
 characters!:EntityTable<Character,"id">;conversations!:EntityTable<Conversation,"id">;messages!:EntityTable<Message,"id">;presets!:EntityTable<Preset,"id">;loreBooks!:EntityTable<LoreBook,"id">;memories!:EntityTable<Memory,"id">;feedPosts!:EntityTable<FeedPost,"id">;memoryExtractionBatches!:EntityTable<MemoryExtractionBatch,"id">;memoryExtractionCursors!:EntityTable<MemoryExtractionCursor,"key">;imageAssets!:EntityTable<ImageAsset,"id">;mediaAssets!:EntityTable<MediaAsset,"id">;stickerPacks!:EntityTable<StickerPack,"id">;meetSessions!:EntityTable<MeetSession,"id">;mallCatalogItems!:EntityTable<MallCatalogItem,"id">;mallCartItems!:EntityTable<MallCartItem,"id">;mallOrders!:EntityTable<MallOrder,"id">;walletTransactions!:EntityTable<WalletTransaction,"id">;forumServers!:EntityTable<ForumServer,"id">;forumChannels!:EntityTable<ForumChannel,"id">;forumPosts!:EntityTable<ForumPost,"id">;backgroundTasks!:EntityTable<BackgroundTask,"id">;memoryVectors!:EntityTable<MemoryVector,"memoryId">;characterPhoneStates!:EntityTable<CharacterPhoneState,"id">;musicTracks!:EntityTable<MusicTrack,"id">;musicFiles!:EntityTable<MusicFile,"id">;musicPlaylists!:EntityTable<MusicPlaylist,"id">;listeningSessions!:EntityTable<ListeningSession,"id">;musicEvents!:EntityTable<MusicEvent,"id">;coupleIslands!:EntityTable<CoupleIsland,"id">;coupleIslandObjects!:EntityTable<CoupleIslandObject,"id">;coupleIslandEntries!:EntityTable<CoupleIslandEntry,"id">;coupleIslandEvents!:EntityTable<CoupleIslandEvent,"id">;settings!:EntityTable<SettingRecord,"key">;
 constructor(){
  super("mira-pocket-os");
  this.version(1).stores({characters:"id,updatedAt,lastActiveAt",conversations:"id,type,lastActivityAt,*memberIds",messages:"id,conversationId,createdAt,senderId",presets:"id,updatedAt",loreBooks:"id,updatedAt",memories:"id,characterId,conversationId,kind,importance",feedPosts:"id,authorId,createdAt",settings:"key"});
  this.version(2).stores({characters:coreStores.characters,conversations:coreStores.conversations,messages:"id,conversationId,createdAt,senderId",presets:coreStores.presets,loreBooks:coreStores.loreBooks,memories:coreStores.memories,feedPosts:coreStores.feedPosts,memoryExtractionBatches:coreStores.memoryExtractionBatches,memoryExtractionCursors:coreStores.memoryExtractionCursors,settings:coreStores.settings});
  this.version(3).stores({characters:coreStores.characters,conversations:coreStores.conversations,messages:"id,conversationId,createdAt,senderId",presets:coreStores.presets,loreBooks:coreStores.loreBooks,memories:coreStores.memories,feedPosts:coreStores.feedPosts,memoryExtractionBatches:coreStores.memoryExtractionBatches,memoryExtractionCursors:coreStores.memoryExtractionCursors,imageAssets:coreStores.imageAssets,settings:coreStores.settings});
  this.version(4).stores({...coreStores,meetSessions:null});
  this.version(5).stores({...coreStores,meetSessions:null}).upgrade(async tx=>{await tx.table("memoryExtractionBatches").where("source").equals("feed").delete();await tx.table("memoryExtractionCursors").filter((cursor:{key:string})=>cursor.key.includes(":feed:")).delete()});
  this.version(6).stores({...coreStores,meetSessions:null}).upgrade(async tx=>{const [books,characters,conversations]=await Promise.all([tx.table("loreBooks").toArray(),tx.table("characters").toArray(),tx.table("conversations").toArray()]);for(const book of books){if(book.mount)continue;const characterIds=characters.filter((character:{loreBookIds?:string[]})=>character.loreBookIds===undefined||character.loreBookIds.includes(book.id)).map((character:{id:string})=>character.id),conversationIds=conversations.filter((conversation:{loreBookIds:string[]})=>conversation.loreBookIds?.includes(book.id)).map((conversation:{id:string})=>conversation.id),mode=characters.length>0&&characterIds.length===characters.length?"global":characterIds.length||conversationIds.length?"selected":"none";await tx.table("loreBooks").update(book.id,{mount:{mode,characterIds:mode==="selected"?characterIds:[],conversationIds:mode==="selected"?conversationIds:[]}})}});
  this.version(7).stores(coreStores);
  this.version(8).stores(coreStores);
  this.version(9).stores(coreStores);
  this.version(10).stores(coreStores);
  this.version(11).stores(coreStores).upgrade(async tx=>{const hash=(value:string)=>{let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)};const memories=await tx.table("memories").toArray();for(const memory of memories){const importance=memory.importance<=5?Math.min(10,Math.max(1,memory.importance*2)):Math.min(10,Math.max(1,memory.importance));await tx.table("memories").update(memory.id,{importance,title:memory.title,meaning:memory.meaning,sourceType:memory.sourceType??(memory.source==="用户手动记录"?"manual":"chat"),sourceIds:memory.sourceIds??[],sourceSnapshot:memory.sourceSnapshot??memory.content,occurredAt:memory.occurredAt??memory.createdAt,topics:memory.topics??[],entities:memory.entities??[],confidence:memory.confidence??.8,valence:memory.valence??.5,arousal:memory.arousal??.2,activationCount:memory.activationCount??0,reinforcementCount:memory.reinforcementCount??0,state:memory.state??"active",digested:memory.digested??memory.kind==="summary",contentHash:memory.contentHash??hash(memory.content)})}const characters=await tx.table("characters").toArray();for(const character of characters){const current=character.memoryExtractionSettings;await tx.table("characters").update(character.id,{memoryExtractionSettings:{enabled:current?.enabled??true,mode:current?.mode??"auto",chatThreshold:current?.chatThreshold??50,maxMemoriesPerBatch:current?.maxMemoriesPerBatch??8,includeSummary:current?.includeSummary??true,autoSaveHighConfidence:current?.autoSaveHighConfidence??true,meetMemoryEnabled:current?.meetMemoryEnabled??true}})}});
  this.version(12).stores({...coreStores,characterPhoneStates:"id,characterId,updatedAt,lastSyncedAt",musicTracks:null,musicFiles:null,musicPlaylists:null,listeningSessions:null,musicEvents:null});
  this.version(13).stores({...coreStores,characterPhoneStates:"id,characterId,updatedAt,lastSyncedAt"});
  this.version(14).stores({...coreStores,characterPhoneStates:"id,characterId,updatedAt,lastSyncedAt",...islandStores});
  this.version(15).stores({...coreStores,characterPhoneStates:"id,characterId,updatedAt,lastSyncedAt",...islandStores});
 }
}
export const db=new MiraDB();
export async function getSetting<T>(key:string,fallback:T):Promise<T>{const row=await db.settings.get(key);return (row?.value as T)??fallback}
export async function setSetting(key:string,value:unknown){await db.settings.put({key,value})}
export const getProvider=async():Promise<ProviderSettings>=>{const raw=await getSetting<Partial<ProviderSettings>>("provider",defaultProvider);return{...defaultProvider,...raw,baseUrl:(raw.baseUrl??defaultProvider.baseUrl).trim(),apiKey:(raw.apiKey??"").trim(),model:(raw.model??defaultProvider.model).trim(),contextBudgetMode:(raw.contextBudgetMode==="custom"?"custom":"auto") as "auto" | "custom",protocol:(raw.protocol&&["auto","openai-compatible","openai-responses","gemini","claude","deepseek-compatible"].includes(raw.protocol as string)?raw.protocol:defaultProvider.protocol),networkMode:raw.networkMode==="relay" && raw.networkModeExplicit===true?"relay":"direct",networkModeExplicit:raw.networkModeExplicit===true,contextWindowTokens:Math.max(8_000,Math.min(1_000_000,Math.trunc(Number(raw.contextWindowTokens??defaultProvider.contextWindowTokens??128_000))))};};
export const getAppSettings=()=>getSetting<AppSettings>("app",{onboarded:false,adultConfirmed:false,sensitiveContent:false,accent:"#7c6df2",userName:"我"});
export const getSpeechSettings=()=>getSetting<SpeechSettings>("speech",defaultSpeechSettings);
export const getModelServiceSettings=()=>getSetting<ModelServiceSettings>("model-services-v1",defaultModelServiceSettings);
export async function getImageGenerationSettings():Promise<ImageGenerationSettings>{
 const raw=await getSetting<Partial<ImageGenerationSettings>|null>("image-generation",null);
 return {
  ...defaultImageGenerationSettings,
  ...raw,
  openai:{...defaultImageGenerationSettings.openai,...(raw?.openai??{})},
  novelai:{...defaultImageGenerationSettings.novelai,...(raw?.novelai??{})}
 };
}
export const getMallWalletSettings=()=>getSetting<MallWalletSettings>("mall-wallet",{balanceCents:520000,initializedAt:Date.now(),updatedAt:Date.now()});
export async function getAppearance():Promise<AppearanceSettings>{const {normalizeAppearance}=await import('./appearance');return normalizeAppearance(await getSetting<AppearanceSettings|null>('appearance',null))}
