import {beforeEach,describe,expect,it,vi} from "vitest";
import {db,getMallWalletSettings} from "./db";
import {addGroupMembers,closePoll,createGroupPoll,createGroupRedPacket,generateCharacterPollVotes,saveDirectorInstruction,splitRedPacket,voteInPoll} from "./groupFeatures";
import {defaultProvider,type Character,type Conversation,type GroupNpc} from "./types";

const conversation:Conversation={id:"g",schemaVersion:1,createdAt:1,updatedAt:1,title:"群聊",type:"group",memberIds:["a","b","c"],presetIds:[],loreBookIds:[],lastActivityAt:1,chatSettings:{bubbleStyle:"inherit",characterAvatarSize:36,fontScale:92,userInGroup:true}};
const character=(id:string,name:string):Character=>({id,schemaVersion:1,createdAt:1,updatedAt:1,name,avatar:"",bio:"",personality:"",speakingStyle:"",background:"",language:"中文",proactive:{messages:false,timeAware:false,frequency:"low",quietStart:"23:00",quietEnd:"08:00",catchupLimit:1,dailyLimit:1},relationship:{intimacy:0,trust:0,mood:"平静",recentEvents:[]},lastActiveAt:1,contactState:{status:"friend"}});
describe("group tools",()=>{
 beforeEach(async()=>{await db.delete();await db.open();await db.conversations.add(conversation);await db.characters.bulkAdd([character("a","甲"),character("b","乙"),character("c","丙")]);await db.settings.put({key:"mall-wallet",value:{balanceCents:10000,initializedAt:1,updatedAt:1}})});
 it("splits every cent and creates an idempotent red packet",async()=>{expect(splitRedPacket(100,3,()=>.2).reduce((sum,value)=>sum+value,0)).toBe(100);const first=await createGroupRedPacket({conversation,members:await db.characters.toArray(),totalAmountCents:1000,packetCount:2,note:"开心",eventId:"event",random:()=>.1}),second=await createGroupRedPacket({conversation,members:await db.characters.toArray(),totalAmountCents:1000,packetCount:2,note:"开心",eventId:"event",random:()=>.1}),attachment=first.attachments?.[0];expect(first.id).toBe(second.id);expect(attachment?.type).toBe("red-packet");if(attachment?.type==="red-packet"){expect(attachment.claims).toHaveLength(2);expect(attachment.claims.reduce((sum,claim)=>sum+claim.amountCents,0)).toBe(1000)}expect((await getMallWalletSettings()).balanceCents).toBe(9000);expect(await db.walletTransactions.count()).toBe(1)});
 it("stores user and character poll votes and closes the poll",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response(JSON.stringify({choices:[{message:{content:'{"optionIds":["invalid"]}'}}]}),{status:200})));const message=await createGroupPoll({conversation,question:"去哪",mode:"multiple",options:["海边","公园"],createdBy:"user"});await generateCharacterPollVotes(message.id,await db.characters.toArray(),{...defaultProvider, networkMode: "direct" as const,apiKey:"key"});let poll=(await db.messages.get(message.id))?.attachments?.find(item=>item.type==="poll");expect(poll?.type).toBe("poll");if(!poll||poll.type!=="poll")return;expect(poll.votes.filter(vote=>vote.voterType==="character")).toHaveLength(3);await voteInPoll(message.id,[poll.options[0].id],"我");await closePoll(message.id);poll=(await db.messages.get(message.id))?.attachments?.find(item=>item.type==="poll");expect(poll?.type==="poll"&&poll.state).toBe("closed");expect(poll?.type==="poll"&&poll.votes.some(vote=>vote.voterType==="user")).toBe(true)});
 it("adds a group-only NPC and lets it claim red packets and vote",async()=>{const npc:GroupNpc={id:"npc-1",name:"小满",age:"22",identity:"书店店员",basicInfo:"喜欢推理小说",persona:"安静但很细心",speakingStyle:"语气温和",active:true,createdAt:1,updatedAt:1};await addGroupMembers({conversation,memberIds:[],npcs:[npc]});const saved=await db.conversations.get(conversation.id);expect(saved?.groupNpcs?.[0]).toMatchObject({id:"npc-1",active:true});const event=await db.messages.where("conversationId").equals(conversation.id).filter(message=>message.kind==="group-event").first();expect(event?.content).toContain("小满");const packet=await createGroupRedPacket({conversation:{...conversation,groupNpcs:[npc]},members:[],npcs:[npc],totalAmountCents:100,packetCount:1,note:"欢迎",random:()=>0}),red=packet.attachments?.find(item=>item.type==="red-packet");expect(red?.type).toBe("red-packet");if(red?.type==="red-packet")expect(red.claims[0]).toMatchObject({participantType:"npc",participantId:"npc-1",participantName:"小满",amountCents:100});vi.stubGlobal("fetch",vi.fn(async()=>new Response(JSON.stringify({choices:[{message:{content:'{"optionIds":["invalid"]}'}}]}),{status:200})));const pollMessage=await createGroupPoll({conversation,question:"今晚吃什么",mode:"single",options:["面","饭"],createdBy:"user"});await generateCharacterPollVotes(pollMessage.id,[],{...defaultProvider, networkMode: "direct" as const,apiKey:"key"},[npc]);const poll=(await db.messages.get(pollMessage.id))?.attachments?.find(item=>item.type==="poll");expect(poll?.type==="poll"&&poll.votes.some(vote=>vote.voterType==="npc"&&vote.voterId==="npc-1")).toBe(true)}); it("saves private director instructions as non-chat system messages",async()=>{const message=await saveDirectorInstruction({...conversation,chatSettings:{...conversation.chatSettings!,userInGroup:false}},"让他们讨论晚餐");expect(message).toMatchObject({senderType:"system",kind:"director",visibility:"private",content:"让他们讨论晚餐"})});
});