import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {db} from "./db";
import {saveModelServiceSettings} from "./modelServices";
import {characterVisualHash,compileImagePromptPlan,ensureCharacterVisualProfile,IMAGE_DIRECTOR_INSTRUCTION,reviewFaceConsistency,validCharacterVisualProfile} from "./imageDirector";
import {defaultModelServiceSettings,defaultProvider,SCHEMA_VERSION,type Character,type Conversation,type LoreBook,type ProviderSettings} from "./types";

const provider:ProviderSettings={...defaultProvider, networkMode: "direct" as const,apiKey:"key",baseUrl:"https://primary.test/v1",model:"chat",stream:false,timeoutMs:1000};
const character:Character={id:"c",schemaVersion:SCHEMA_VERSION,createdAt:1,updatedAt:1,name:"顾言",avatar:"",bio:"28岁的急诊医生，黑色短发，左眼下有淡痣",personality:"克制冷淡",speakingStyle:"简短",background:"临海市医院",language:"中文",chatSettings:{language:"中文",contextLimit:30,stream:false,feedImage:{enabled:true,appearancePrompt:"黑色短发，窄脸，左眼下淡痣",referenceAssetId:"ref"}},proactive:{messages:false,timeAware:false,frequency:"medium",quietStart:"23:00",quietEnd:"08:00",catchupLimit:1,dailyLimit:3},relationship:{intimacy:20,trust:20,mood:"疲惫",recentEvents:[]},lastActiveAt:1};
const conversation:Conversation={id:"v",schemaVersion:SCHEMA_VERSION,createdAt:1,updatedAt:1,title:"顾言",type:"private",memberIds:["c"],presetIds:[],loreBookIds:[],lastActivityAt:1};
const profile={apparentAge:"28岁",faceIdentity:"窄脸、黑眼、薄唇、左眼下淡痣",immutableFeatures:["外观年龄约28岁","左眼下淡痣"],signatureFeatures:["黑色短发"],typicalAppearance:["深色衣服"],photoHabits:["不直视镜头"],forbiddenChanges:["换脸","幼态化"]};
const plan={intent:"selfie",subjects:[{characterId:"c",name:"顾言",appearance:"黑色短发",faceIdentity:"窄脸和左眼下淡痣",expression:"疲惫克制",pose:"前置自拍",clothing:"深色衬衫"}],faceLock:{referenceAssetId:"ref",immutableFeatures:["左眼下淡痣"],allowedTemporaryChanges:["服装"],forbiddenChanges:["换脸"]},environment:"医院休息室",composition:"略微偏心",camera:"前置摄像头",lighting:"冷色灯光",mood:"疲惫",continuity:[],requiredDetails:["淡痣"],forbiddenDetails:["用户入镜"],openaiPrompt:"Preserve the exact same face. Hospital selfie.",novelaiPrompt:"same character, black hair, mole under left eye, selfie",negativePrompt:"different face, text",visualSummary:"顾言在医院休息室拍了一张疲惫的自拍。",textImageDescription:"医院休息室里，顾言穿着深色衬衫，神情疲惫，窗外天快亮了。",companionMessages:["天快亮了。"]};
function response(content:string){return new Response(JSON.stringify({choices:[{message:{content}}]}),{status:200,headers:{"Content-Type":"application/json"}})}
beforeEach(async()=>{await db.delete();await db.open()});
afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks()});

describe("image director",()=>{
 it("contains face lock, persona photography, lore priority, continuity and camera rules",()=>{expect(IMAGE_DIRECTOR_INSTRUCTION).toContain("锁脸高于默认美化");expect(IMAGE_DIRECTOR_INSTRUCTION).toContain("图片必须像这个角色会拍摄或分享的内容");expect(IMAGE_DIRECTOR_INSTRUCTION).toContain("世界书原文高于概括");expect(IMAGE_DIRECTOR_INSTRUCTION).toContain("同一场景保持服装");expect(IMAGE_DIRECTOR_INSTRUCTION).toContain("普通自拍使用合理前置摄像头视角");expect(IMAGE_DIRECTOR_INSTRUCTION).toContain("不擅自加入用户")});
 it("invalidates visual identity after appearance prompt or reference changes",()=>{const sourceHash=characterVisualHash(character),visualProfile={...profile,sourceHash,updatedAt:1};expect(validCharacterVisualProfile({...character,visualProfile})).toEqual(visualProfile);expect(validCharacterVisualProfile({...character,chatSettings:{...character.chatSettings!,feedImage:{...character.chatSettings!.feedImage!,appearancePrompt:"银色长发"}},visualProfile})).toBeUndefined();expect(validCharacterVisualProfile({...character,chatSettings:{...character.chatSettings!,feedImage:{...character.chatSettings!.feedImage!,referenceAssetId:"new"}},visualProfile})).toBeUndefined()});
 it("compiles and stores the visual profile then creates a provider-specific plan",async()=>{await db.characters.add(character);const fetchMock=vi.fn().mockResolvedValueOnce(response(JSON.stringify(profile))).mockResolvedValueOnce(response(JSON.stringify(plan)));vi.stubGlobal("fetch",fetchMock);const result=await compileImagePromptPlan({character,conversation,loreBooks:[] as LoreBook[],memories:[],messages:[],request:"夜班结束后的自拍",provider,referenceAssetId:"ref"});expect(result.plan).toMatchObject({intent:"selfie",openaiPrompt:plan.openaiPrompt,novelaiPrompt:plan.novelaiPrompt,textImageDescription:plan.textImageDescription});expect((await db.characters.get("c"))?.visualProfile).toMatchObject(profile);expect(fetchMock).toHaveBeenCalledTimes(2)});
 it("falls back to a locked text-image plan when compilation fails",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(response("not json")));const result=await compileImagePromptPlan({character,conversation,loreBooks:[],memories:[],messages:[],request:"窗外的雨",provider,referenceAssetId:"ref"});expect(result.plan.openaiPrompt).toContain("Preserve the exact established facial identity");expect(result.plan.faceLock.referenceAssetId).toBe("ref");expect(result.plan.textImageDescription).toContain("窗外的雨")});
 it("compares reference and generated images through the configured vision service",async()=>{const vision={...provider,baseUrl:"https://vision.test/v1",apiKey:"vision",model:"vision"};await saveModelServiceSettings({...defaultModelServiceSettings,vision:{enabled:true,provider:vision,instruction:"检查图片"}});const fetchMock=vi.fn().mockResolvedValue(response(JSON.stringify({passed:false,score:.61,mismatches:["脸型不同"]})));vi.stubGlobal("fetch",fetchMock);await expect(reviewFaceConsistency("data:image/png;base64,cmVm","data:image/png;base64,bmV3")).resolves.toEqual({passed:false,score:.61,mismatches:["脸型不同"]});const body=JSON.parse(String(fetchMock.mock.calls[0][1]?.body));expect(body.messages[1].content.filter((item:any)=>item.type==="image_url")).toHaveLength(2)});
});