import mammoth from "mammoth";
import type {Character,Conversation,LoreBook,LoreEntry,LoreInsertionPosition,LoreMount,Scope} from "./types";
import {SCHEMA_VERSION,now,uid} from "./types";

export const DEFAULT_LORE_SCAN_DEPTH=20;
export const DEFAULT_LORE_BUDGET=3000;
export const LORE_INSERTION_OPTIONS:ReadonlyArray<{value:LoreInsertionPosition;label:string;description:string}>=[
 {value:"base-rules",label:"基础规则（最前）",description:"适合世界法则、时代规则和不可忽略的基础限制；位于固定演绎规则之后、角色资料之前。"},
 {value:"after-character",label:"角色资料后（默认）",description:"适合角色身份、种族、能力、组织和长期地点设定；保持旧条目的现有注入效果。"},
 {value:"after-memory",label:"剧情资料区",description:"适合当前事件、地点状态、任务和剧情阶段；位于记忆之后、聊天记录之前。"},
 {value:"before-history",label:"对话记录前",description:"适合需要据此理解整段近期对话的背景资料；放在最近聊天记录之前。"},
 {value:"before-user",label:"本轮消息前（最近）",description:"适合只需要本轮重点关注的设定；紧邻用户最新输入之前。"},
];
export function loreInsertionPositionOf(entry:Pick<LoreEntry,"insertionPosition">):LoreInsertionPosition{return LORE_INSERTION_OPTIONS.some(option=>option.value===entry.insertionPosition)?entry.insertionPosition!:"after-character"}
export function loreEntriesBlock(entries:Array<Pick<LoreDecision,"bookName"|"title"|"id"|"content">>,heading="本轮相关世界书原文（原文高于概括）"){return entries.length?`${heading}：\n${entries.map(entry=>`[${entry.bookName}/${entry.title||entry.id}] ${entry.content}`).join("\n")}`:""}
export function groupLoreByInsertion(entries:LoreDecision[]){const grouped:Record<LoreInsertionPosition,LoreDecision[]>={"base-rules":[],"after-character":[],"after-memory":[],"before-history":[],"before-user":[]};for(const entry of entries)grouped[loreInsertionPositionOf(entry)].push(entry);return grouped}

export type LoreSkipReason="世界书已停用"|"世界书未挂载"|"条目已停用"|"作用范围不匹配"|"主关键词未命中"|"辅助关键词不满足"|"概率未通过"|"注入预算不足";
export interface LoreDecision extends LoreEntry{bookId:string;bookName:string;matched:boolean;injected:boolean;reason?:LoreSkipReason;estimatedChars:number;order?:number;usedBudget:number;remainingBudget:number}
export interface LoreEvaluationInput{books:LoreBook[];texts:string[];characterId:string;conversationId:string;character?:Character;conversation?:Conversation;budget?:number;seed?:string;forceAll?:boolean}
export type LoreImportMode="single"|"headings";
export interface LoreImportSection{title:string;content:string}
export interface LoreImportPreview{format:"txt"|"docx";mode:LoreImportMode;books:LoreBook[];warnings:string[];entryCount:number;sourceText:string;fileName:string;headingSections:LoreImportSection[]}
export interface LoreExportFile{format:"chachaji-lorebook";formatVersion:1;exportedAt:string;books:LoreBook[]}

const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value));
const specificity=(scope:Scope)=>scope.type==="conversation"?3:scope.type==="character"?2:1;
export function scopeMatches(scope:Scope,characterId:string,conversationId:string){return scope.type==="global"||(scope.type==="character"&&scope.id===characterId)||(scope.type==="conversation"&&scope.id===conversationId)}
export function normalizeLoreMount(mount?:Partial<LoreMount>):LoreMount|undefined{if(!mount)return undefined;const mode=mount.mode==="global"||mount.mode==="none"?mount.mode:"selected";return{mode,characterIds:[...new Set((mount.characterIds??[]).filter(Boolean))],conversationIds:[...new Set((mount.conversationIds??[]).filter(Boolean))]}}
export function isLoreBookMounted(book:LoreBook,characterId:string,conversationId:string,character?:Character,conversation?:Conversation){const mount=normalizeLoreMount(book.mount);if(mount?.mode==="global")return true;if(mount?.mode==="none")return false;if(mount?.mode==="selected")return mount.characterIds.includes(characterId)||mount.conversationIds.includes(conversationId);if(!character&&!conversation)return true;const personal=character?.loreBookIds===undefined||character.loreBookIds.includes(book.id),chat=conversation?.loreBookIds.includes(book.id)??false;return Boolean(personal||chat)}
function stablePercent(seed:string){let hash=2166136261;for(let i=0;i<seed.length;i++){hash^=seed.charCodeAt(i);hash=Math.imul(hash,16777619)}return (hash>>>0)%100}
function scanText(texts:string[],depth:number|undefined){const safe=depth===undefined?texts:depth<=0?texts:texts.slice(-Math.max(1,Math.floor(depth)));return safe.join("\n").toLocaleLowerCase()}
function normalizedProbability(entry:LoreEntry){return clamp(Number.isFinite(entry.probability)?Number(entry.probability):100,0,100)}
function reasonDecision(entry:LoreEntry,book:LoreBook,input:LoreEvaluationInput):LoreSkipReason|undefined{if(!book.enabled)return"世界书已停用";if(!isLoreBookMounted(book,input.characterId,input.conversationId,input.character,input.conversation))return"世界书未挂载";if(!entry.enabled)return"条目已停用";if(!scopeMatches(entry.scope,input.characterId,input.conversationId))return"作用范围不匹配";if(input.forceAll)return;const depth=book.triggerSettings?.defaultScanDepth??DEFAULT_LORE_SCAN_DEPTH,haystack=scanText(input.texts,depth),constant=entry.constant??entry.keywords.length===0,primary=entry.keywords.map(value=>value.trim().toLocaleLowerCase()).filter(Boolean);if(!constant&&(!primary.length||!primary.some(key=>haystack.includes(key))))return"主关键词未命中";const secondary=(entry.secondaryKeywords??[]).map(value=>value.trim().toLocaleLowerCase()).filter(Boolean);if(secondary.length){const passed=(entry.secondaryLogic??"and")==="or"?secondary.some(key=>haystack.includes(key)):secondary.every(key=>haystack.includes(key));if(!passed)return"辅助关键词不满足"}const probability=normalizedProbability(entry);if(probability<100&&stablePercent(`${input.conversationId}:${entry.id}:${input.seed??input.texts.join("\n")}`)>=probability)return"概率未通过"}
export function evaluateLore(input:LoreEvaluationInput){const indexed=input.books.flatMap((book,bookIndex)=>book.entries.map((entry,entryIndex)=>({book,entry,bookIndex,entryIndex}))).sort((a,b)=>specificity(b.entry.scope)-specificity(a.entry.scope)||b.entry.priority-a.entry.priority||a.bookIndex-b.bookIndex||a.entryIndex-b.entryIndex),globalLimit=Math.max(0,input.budget??Math.max(DEFAULT_LORE_BUDGET,...input.books.map(book=>book.triggerSettings?.maxContextChars??DEFAULT_LORE_BUDGET))),decisions:LoreDecision[]=[];let injectedOrder=0,used=0;for(const item of indexed){const {book,entry}=item,estimatedChars=entry.content.length;let reason=reasonDecision(entry,book,input),matched=!reason,injected=false;if(!reason&&used+estimatedChars>globalLimit)reason="注入预算不足";else if(!reason){injected=true;injectedOrder+=1;used+=estimatedChars}decisions.push({...entry,bookId:book.id,bookName:book.name,matched,injected,reason,estimatedChars,order:injected?injectedOrder:undefined,usedBudget:used,remainingBudget:Math.max(0,globalLimit-used)})}return decisions}
export function matchLore(books:LoreBook[],text:string,characterId:string,conversationId:string,budget=DEFAULT_LORE_BUDGET){return evaluateLore({books,texts:[text],characterId,conversationId,budget,seed:text}).filter(item=>item.injected)}

function cleanKeywords(value:unknown){if(Array.isArray(value))return value.map(String).map(item=>item.trim()).filter(Boolean);if(typeof value==="string")return value.split(/[，,\n]/).map(item=>item.trim()).filter(Boolean);return[]}
function cleanScope(value:unknown):Scope{const scope=value as Partial<Scope>|undefined;if(scope?.type==="character"||scope?.type==="conversation")return scope.id?{type:scope.type,id:String(scope.id)}:{type:"global"};return{type:"global"}}
function cleanEntry(raw:unknown,index:number,warnings:string[]):LoreEntry|null{const value=(raw&&typeof raw==="object"?raw:{}) as Record<string,unknown>,content=typeof value.content==="string"?value.content.trim():"";if(!content){warnings.push(`第 ${index+1} 个条目缺少正文，已跳过`);return null}const timestamp=now();return{id:uid(),title:typeof value.title==="string"?value.title.trim():typeof value.comment==="string"?value.comment.trim():`条目 ${index+1}`,keywords:cleanKeywords(value.keywords??value.key),secondaryKeywords:cleanKeywords(value.secondaryKeywords??value.keysecondary),secondaryLogic:value.secondaryLogic==="or"||value.selectiveLogic==="or"||value.selectiveLogic===1?"or":"and",constant:Boolean(value.constant),probability:clamp(Number(value.useProbability===false?100:value.probability??100)||0,0,100),insertionPosition:LORE_INSERTION_OPTIONS.some(option=>option.value===value.insertionPosition)?value.insertionPosition as LoreInsertionPosition:undefined,content,priority:clamp(Math.floor(Number(value.priority??value.order??50)||0),0,999),enabled:value.enabled!==false&&value.disable!==true,scope:cleanScope(value.scope),createdAt:typeof value.createdAt==="number"?value.createdAt:timestamp,updatedAt:typeof value.updatedAt==="number"?value.updatedAt:timestamp}}
function cleanBook(raw:unknown,index:number,warnings:string[],fallbackName:string):LoreBook{const value=(raw&&typeof raw==="object"?raw:{}) as Record<string,unknown>,rawEntries=Array.isArray(value.entries)?value.entries:value.entries&&typeof value.entries==="object"?Object.values(value.entries as object):[],entries=rawEntries.map((entry,i)=>cleanEntry(entry,i,warnings)).filter((entry):entry is LoreEntry=>Boolean(entry)),timestamp=now(),mount=normalizeLoreMount(value.mount as Partial<LoreMount>|undefined),settings=value.triggerSettings as Partial<LoreBook["triggerSettings"]>|undefined;return{id:uid(),schemaVersion:SCHEMA_VERSION,createdAt:timestamp,updatedAt:timestamp,name:(typeof value.name==="string"&&value.name.trim())||`${fallbackName}${index?` ${index+1}`:""}`,description:typeof value.description==="string"?value.description.trim():"",entries,enabled:value.enabled!==false,mount:mount??{mode:"none",characterIds:[],conversationIds:[]},triggerSettings:{defaultScanDepth:clamp(Math.floor(Number(settings?.defaultScanDepth??DEFAULT_LORE_SCAN_DEPTH)),1,200),...(Number.isFinite(Number(settings?.maxContextChars))&&Number(settings?.maxContextChars)>0?{maxContextChars:Math.floor(Number(settings?.maxContextChars))}:{})}}}
function loreDocumentName(fileName:string){return fileName.replace(/\.[^.]+$/,"").trim()||"导入的世界书"}
function extractDocumentKeywords(text:string){const keywords:string[]=[];const content=text.replace(/^关键词\s*[:：]\s*(.+)$/gmu,(_,value:string)=>{keywords.push(...cleanKeywords(value));return ""}).replace(/\n{3,}/g,"\n\n").trim();return{keywords:[...new Set(keywords)],content}}
function explicitTextHeading(line:string){const markdown=line.match(/^#{1,6}\s+(.+)$/),label=line.match(/^标题\s*[:：]\s*(.+)$/);return(markdown?.[1]??label?.[1])?.trim()}
function textHeadingSections(text:string,fileName:string){const sections:LoreImportSection[]=[],preamble:string[]=[];let title="",body:string[]=[];const flush=()=>{if(!title)return;const prefix=sections.length===0&&preamble.length?preamble.join("\n").trim():"";const content=[prefix,body.join("\n").trim()].filter(Boolean).join("\n\n");if(content)sections.push({title,content});body=[]};for(const raw of text.replace(/^\uFEFF/,"").split(/\r?\n/)){const heading=explicitTextHeading(raw.trim());if(heading){flush();title=heading;continue}if(title)body.push(raw);else preamble.push(raw)}flush();if(!sections.length)return[];if(preamble.length&&!sections[0].content.startsWith(preamble.join("\n").trim()))sections[0].content=[preamble.join("\n").trim(),sections[0].content].filter(Boolean).join("\n\n");return sections}
function htmlHeadingSections(html:string){if(typeof DOMParser==="undefined")return[];const document=new DOMParser().parseFromString(html,"text/html"),sections:LoreImportSection[]=[],preamble:string[]=[];let current:{title:string;lines:string[]}|undefined;const flush=()=>{if(!current)return;const prefix=sections.length===0&&preamble.length?preamble.join("\n").trim():"",content=[prefix,current.lines.join("\n").trim()].filter(Boolean).join("\n\n");if(content)sections.push({title:current.title,content});current=undefined};for(const node of Array.from(document.body.children)){const text=(node.textContent??"").trim();if(!text)continue;if(/^H[1-6]$/.test(node.tagName)){flush();current={title:text,lines:[]}}else if(current)current.lines.push(text);else preamble.push(text)}flush();return sections}
function loreEntry(title:string,content:string,timestamp:number):LoreEntry|undefined{const extracted=extractDocumentKeywords(content);if(!extracted.content)return;return{id:uid(),title:title.trim()||"文档正文",keywords:extracted.keywords,constant:extracted.keywords.length===0,secondaryKeywords:[],secondaryLogic:"and",probability:100,content:extracted.content,priority:50,enabled:true,scope:{type:"global"},createdAt:timestamp,updatedAt:timestamp}}
function documentBook(text:string,fileName:string,warnings:string[],format:"txt"|"docx",mode:LoreImportMode,headingSections:LoreImportSection[]){const name=loreDocumentName(fileName),timestamp=now();let entries:LoreEntry[]=[];if(mode==="headings"&&headingSections.length){entries=headingSections.map(section=>loreEntry(section.title,section.content,timestamp)).filter((entry):entry is LoreEntry=>Boolean(entry));if(!entries.length)warnings.push("没有识别到带正文的标题，已按整篇文档导入")}if(!entries.length){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/),first=lines[0]?.trim()??"",explicit=explicitTextHeading(first),docxTitle=headingSections[0]?.title&&headingSections[0].title===first?first:"",title=explicit||docxTitle||name,content=explicit||docxTitle?lines.slice(1).join("\n").trim():text.replace(/^\uFEFF/,"").trim(),entry=loreEntry(title,content,timestamp);if(entry)entries=[entry]}return{id:uid(),schemaVersion:SCHEMA_VERSION,createdAt:timestamp,updatedAt:timestamp,name,description:`从 ${format.toUpperCase()} 导入`,entries,enabled:true,mount:{mode:"none",characterIds:[],conversationIds:[]},triggerSettings:{defaultScanDepth:DEFAULT_LORE_SCAN_DEPTH}} satisfies LoreBook}
function validateLoreDocument(text:string,fileName:string){const extension=fileName.toLowerCase().match(/\.[^.]+$/)?.[0]??"";if(extension!==".txt"&&extension!==".docx")throw new Error("不支持 JSON 世界书，只能选择 TXT 或 DOCX 文件。");if(text.length>10*1024*1024)throw new Error("世界书文件不能超过 10MB");const trimmed=text.trim();if(!trimmed)throw new Error("导入文件为空");if(trimmed.startsWith("{")||trimmed.startsWith("["))throw new Error("不支持 JSON 世界书，只能导入 TXT 或 DOCX 文本内容。");return extension===".docx"?"docx" as const:"txt" as const}
function buildLoreImportPreview(text:string,fileName:string,mode:LoreImportMode,headingSections:LoreImportSection[]){const warnings:string[]=[],format=validateLoreDocument(text,fileName),sections=headingSections.length?headingSections:textHeadingSections(text,fileName),book=documentBook(text,fileName,warnings,format,mode,sections);if(!book.entries.length)throw new Error(`${format.toUpperCase()} 中没有可导入的条目`);if(mode==="headings"&&!sections.length)warnings.push("没有识别到明确标题，已按整篇文档导入为一个条目");return{format,mode,books:[book],warnings,entryCount:book.entries.length,sourceText:text,fileName,headingSections:sections} satisfies LoreImportPreview}
export function parseLoreImport(text:string,fileName="世界书.txt",mode:LoreImportMode="single"):LoreImportPreview{return buildLoreImportPreview(text,fileName,mode,[])}
export function changeLoreImportMode(preview:LoreImportPreview,mode:LoreImportMode){return buildLoreImportPreview(preview.sourceText,preview.fileName,mode,preview.headingSections)}
export const LORE_DOCUMENT_ACCEPT=".txt,.docx,text/plain,application/vnd.openxmlformats-officedocument.wordprocessingml.document";
export async function readLoreImportFile(file:File):Promise<LoreImportPreview>{const extension=file.name.toLowerCase().match(/\.[^.]+$/)?.[0]??"";if(extension!==".txt"&&extension!==".docx")throw new Error("不支持 JSON 世界书，只能选择 TXT 或 DOCX 文件。");if(file.size>10*1024*1024)throw new Error("世界书文件不能超过 10MB");try{if(extension===".txt")return parseLoreImport(await file.text(),file.name);const arrayBuffer=await file.arrayBuffer(),[raw,html]=await Promise.all([mammoth.extractRawText({arrayBuffer}),mammoth.convertToHtml({arrayBuffer})]);return buildLoreImportPreview(raw.value,file.name,"single",htmlHeadingSections(html.value))}catch(error){if(error instanceof Error&&/不支持 JSON|不能超过|导入文件为空|没有可导入/.test(error.message))throw error;throw new Error(extension===".docx"?"无法读取这个 DOCX 文件，请确认它是有效的 Word 文档。":"无法读取这个 TXT 文件，请确认文件编码和内容正常。")} }
export function createLoreExport(books:LoreBook[]):LoreExportFile{return{format:"chachaji-lorebook",formatVersion:1,exportedAt:new Date().toISOString(),books}}
export function uniqueLoreName(name:string,existing:string[]){const used=new Set(existing.map(item=>item.trim().toLocaleLowerCase())),base=name.trim()||"未命名世界书";if(!used.has(base.toLocaleLowerCase()))return base;let index=2;while(used.has(`${base} (${index})`.toLocaleLowerCase()))index++;return`${base} (${index})`}
export async function shareOrDownloadJson(value:unknown,fileName:string){const safe=fileName.replace(/[\\/:*?"<>|]/g,"_"),blob=new Blob([JSON.stringify(value,null,2)],{type:"application/json;charset=utf-8"}),file=new File([blob],safe,{type:blob.type});if(typeof navigator.share==="function"&&(!navigator.canShare||navigator.canShare({files:[file]}))){try{await navigator.share({files:[file],title:safe});return}catch(error){if((error as DOMException)?.name!=="AbortError")console.warn("分享世界书失败，改为下载",error);else return}}const url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=safe;document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}

