import {beforeEach,describe,expect,it,vi} from "vitest";
import {db} from "./db";
import {OpenAIProvider} from "./provider";
import {defaultProvider} from "./types";
import {useStore} from "./store";
import {deleteMeetEntry,editMeetUserEntry,meetEntryPlainText,regenerateMeetCharacterEntry,toggleMeetEntryFavorite,updateMeetScene} from "./meetService";
import type {Character,MeetSession} from "./types";

const userEntry={id:"u1",roundId:"r1",senderType:"user" as const,content:"我推开门，朝你笑了笑。",createdAt:10};
const roleEntry={id:"c1",roundId:"r1",senderType:"character" as const,senderId:"char",prose:"她从窗边回过头。",dialogue:"你来了。",favoritedAt:88,createdAt:11};
const makeSession=(overrides:Partial<MeetSession>={}):MeetSession=>({id:"meet",schemaVersion:1,createdAt:1,updatedAt:1,participantIds:["char"],initiator:"user",scene:{opening:"见面吧"},suggestionsEnabled:false,status:"active",entries:[userEntry,roleEntry],startedAt:1,lastActivityAt:11,...overrides});
const character={id:"char",schemaVersion:1,createdAt:1,updatedAt:1,name:"阿茶",avatar:"",bio:"",personality:"温柔",speakingStyle:"自然",background:"",language:"中文",proactive:{messages:false,timeAware:false,frequency:"low",quietStart:"23:00",quietEnd:"08:00",catchupLimit:1,dailyLimit:1},relationship:{intimacy:0,trust:0,mood:"平静",recentEvents:[]},lastActiveAt:1} as Character;

describe("meet entry actions",()=>{
 beforeEach(async()=>{await db.delete();await db.open();await db.characters.add(character);await db.meetSessions.add(makeSession())});
 it("收藏与取消收藏直接保存在帖子上",async()=>{expect(await toggleMeetEntryFavorite("meet","u1",123)).toBe(123);expect((await db.meetSessions.get("meet"))?.entries[0].favoritedAt).toBe(123);expect(await toggleMeetEntryFavorite("meet","u1",456)).toBeUndefined();expect((await db.meetSessions.get("meet"))?.entries[0].favoritedAt).toBeUndefined()});
 it("只允许编辑进行中的用户帖并支持删除",async()=>{await editMeetUserEntry("meet","u1","  修改后的开场  ");expect((await db.meetSessions.get("meet"))?.entries[0].content).toBe("修改后的开场");await expect(editMeetUserEntry("meet","c1","不允许")).rejects.toThrow("不能编辑");await deleteMeetEntry("meet","u1");expect((await db.meetSessions.get("meet"))?.entries.map(entry=>entry.id)).toEqual(["c1"])});
 it("结束后阻止编辑、删除和重新生成",async()=>{await db.meetSessions.update("meet",{status:"ended"});await expect(editMeetUserEntry("meet","u1","修改")).rejects.toThrow();await expect(deleteMeetEntry("meet","u1")).rejects.toThrow();await expect(regenerateMeetCharacterEntry("meet","c1")).rejects.toThrow()});
 it("原位重新生成角色帖并保留编号与收藏",async()=>{const result=await regenerateMeetCharacterEntry("meet","c1"),saved=await db.meetSessions.get("meet");expect(result.id).toBe("c1");expect(result.favoritedAt).toBe(88);expect(saved?.entries).toHaveLength(2);expect(saved?.entries.filter(entry=>entry.senderType==="user")).toHaveLength(1);expect(saved?.entries.find(entry=>entry.id==="c1")?.dialogue).toBeTruthy()});
 it("开启角色思维链后将内心独白单独保存且不混入帖子正文",async()=>{await db.meetSessions.update("meet",{narrativeSettings:{version:3,minChars:500,maxChars:800,thoughtsEnabled:true,perspective:"third",styleMode:"plain",customStyle:""}});const result=await regenerateMeetCharacterEntry("meet","c1");expect(result.thought).toContain("我推开门");expect(result.thought).toContain("心绪");expect(result.thought!.length).toBeGreaterThan(160);expect(result.prose).not.toContain(result.thought);expect(meetEntryPlainText(result)).not.toContain(result.thought!);expect((await db.meetSessions.get("meet"))?.entries.find(entry=>entry.id==="c1")?.thought).toBe(result.thought)});
  it("低于最少字数时单角色重新生成只紧凑重试一次",async()=>{await db.settings.put({key:"provider",value:{...defaultProvider,networkMode:"direct",apiKey:"test-key",model:"test-model"}});await db.meetSessions.update("meet",{narrativeSettings:{version:3,minChars:100,maxChars:120,thoughtsEnabled:false,perspective:"third",styleMode:"plain",customStyle:""}});const short=JSON.stringify({replies:[{characterId:"char",prose:"短",dialogue:"好"}]}),complete=JSON.stringify({replies:[{characterId:"char",prose:"景".repeat(120),dialogue:"我们继续把话说完。"}]}),chat=vi.spyOn(OpenAIProvider.prototype,"chat").mockResolvedValueOnce(short).mockResolvedValueOnce(complete);const result=await regenerateMeetCharacterEntry("meet","c1");expect(chat).toHaveBeenCalledTimes(2);expect(result.prose).toContain("景".repeat(120));});
 it("单场时间感知设置能够保存且旧记录默认关闭",async()=>{expect((await db.meetSessions.get("meet"))?.timeAware).toBeUndefined();await updateMeetScene("meet",{opening:"继续见面"},false,undefined,true);expect((await db.meetSessions.get("meet"))?.timeAware).toBe(true);await updateMeetScene("meet",{opening:"继续见面"},false);expect((await db.meetSessions.get("meet"))?.timeAware).toBe(true)});
 it("加载时一次迁移旧篇幅并持久保留新版自定义值",async()=>{await db.meetSessions.update("meet",{narrativeSettings:{minChars:200,maxChars:500,thoughtsEnabled:false,perspective:"third",styleMode:"plain",customStyle:""}});await useStore.getState().reload();expect((await db.meetSessions.get("meet"))?.narrativeSettings).toMatchObject({version:3,minChars:200,maxChars:500});await db.meetSessions.update("meet",{narrativeSettings:{version:3,minChars:600,maxChars:900,thoughtsEnabled:false,perspective:"third",styleMode:"plain",customStyle:""}});await useStore.getState().reload();expect((await db.meetSessions.get("meet"))?.narrativeSettings).toMatchObject({version:3,minChars:600,maxChars:900})});
 it("复制正文按小说正文与台词顺序组合",()=>{expect(meetEntryPlainText(roleEntry)).toBe("她从窗边回过头。\n\n你来了。")});
});
