import {z} from "zod";
import {db} from "./db";
import {OpenAIProvider,ProviderError} from "./provider";
import {resolveSecondaryProvider} from "./modelServices";
import {coreSettingOf,personaOf} from "./character";
import {canCharacterInteract} from "./conversationSettings";
import {applyRelationship} from "./rules";
import {lexicalMemorySimilarity,memoryContentHash,normalizedMemory} from "./memory";
import {now,SCHEMA_VERSION,uid,type Character,type MeetSession,type Memory,type MemoryExtractionBatch,type MemoryExtractionSettings,type Message,type ProviderSettings,type StoredMemoryCandidate} from "./types";

export type MemoryCandidate=StoredMemoryCandidate;
type SourceItem={id:string;text:string};
const relationSchema=z.object({kind:z.enum(["positive","negative","neutral"]),importance:z.number(),label:z.string()});
const itemSchema=z.object({kind:z.enum(["fact","plot","relationship"]),title:z.string().optional(),content:z.string(),meaning:z.string().optional(),importance:z.number(),confidence:z.number().optional(),valence:z.number().optional(),arousal:z.number().optional(),topics:z.array(z.string()).optional(),entities:z.array(z.string()).optional(),occurredAt:z.union([z.number(),z.string()]).optional(),sourceIds:z.array(z.string()).optional(),relationshipEvent:relationSchema.optional()});
const clean=(text:string)=>text.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"");
const clamp=(value:number,min:number,max:number)=>Math.max(min,Math.min(max,value));
export const defaultMemoryExtractionSettings=():MemoryExtractionSettings=>({enabled:true,mode:"auto",chatThreshold:50,maxMemoriesPerBatch:8,includeSummary:true,autoSaveHighConfidence:true,meetMemoryEnabled:true});
export const memoryExtractionSettingsOf=(c:Character):MemoryExtractionSettings=>{const current=c.memoryExtractionSettings;return{enabled:current?.enabled??true,mode:current?.mode??"auto",chatThreshold:current?.chatThreshold??50,maxMemoriesPerBatch:current?.maxMemoriesPerBatch??8,includeSummary:current?.includeSummary??true,autoSaveHighConfidence:current?.autoSaveHighConfidence??true,meetMemoryEnabled:current?.meetMemoryEnabled??true}};
export const validMemoryExtractionSettings=(x:Partial<MemoryExtractionSettings>)=>{const max=x.maxMemoriesPerBatch??8,threshold=x.chatThreshold??50;if(max<1||max>12||threshold<10||threshold>200)return false;return x.mode==="manual"||x.mode==="auto"};
export const cursorKey=(characterId:string,source:"chat"|"feed"|"meet",conversationId?:string)=>`${characterId}:${source}:${conversationId??"all"}`;
const normalize=(v:string)=>v.toLowerCase().replace(/[\s\p{P}\p{S}]/gu,"");
const bigrams=(v:string)=>{const n=normalize(v);return new Set(Array.from({length:Math.max(0,n.length-1)},(_,i)=>n.slice(i,i+2)))};
export function similarMemory(a:string,b:string){const x=normalize(a),y=normalize(b);if(!x||!y)return false;if(x===y||x.includes(y)||y.includes(x))return true;const A=bigrams(x),B=bigrams(y),common=[...A].filter(v=>B.has(v)).length;return common/(A.size+B.size-common||1)>=.72}
export function isDuplicateMemory(candidate:Pick<MemoryCandidate,"kind"|"content">,memories:Memory[],characterId:string,conversationId?:string){return memories.some(m=>m.characterId===characterId&&m.kind===candidate.kind&&(!m.conversationId||m.conversationId===conversationId)&&similarMemory(m.content,candidate.content))}
function occurred(value:unknown){if(typeof value==="number"&&Number.isFinite(value))return value;if(typeof value==="string"){const parsed=Date.parse(value);if(Number.isFinite(parsed))return parsed}return now()}
export function validateMemoryCandidates(raw:unknown,maxMemories=8,includeSummary=true):MemoryCandidate[]{const modern=z.object({summary:z.union([z.string(),itemSchema]).optional(),memories:z.array(itemSchema).default([])}).safeParse(raw),legacy=z.object({candidates:z.array(z.object({kind:z.enum(["summary","fact","plot","relationship"]),title:z.string().optional(),content:z.string(),meaning:z.string().optional(),importance:z.number(),confidence:z.number().optional(),valence:z.number().optional(),arousal:z.number().optional(),topics:z.array(z.string()).optional(),entities:z.array(z.string()).optional(),occurredAt:z.union([z.number(),z.string()]).optional(),relationshipEvent:relationSchema.optional()}))}).safeParse(raw);if(!modern.success&&!legacy.success)throw new ProviderError("format","记忆提取结果格式无法识别");const output:MemoryCandidate[]=[];const add=(c:any)=>{const content=String(c.content??"").trim();if(!content)return;if(c.kind==="summary"&&(!includeSummary||output.some(x=>x.kind==="summary")))return;if(c.kind!=="summary"&&output.filter(x=>x.kind!=="summary").length>=maxMemories)return;const rawImportance=Number(c.importance??5),importance=clamp(rawImportance<=5?Math.round(rawImportance*2):Math.round(rawImportance),1,10);output.push({id:uid(),kind:c.kind,title:String(c.title??"").trim()||undefined,content,meaning:String(c.meaning??"").trim()||undefined,importance,confidence:clamp(Number(c.confidence??.72),0,1),valence:clamp(Number(c.valence??.5),0,1),arousal:clamp(Number(c.arousal??.2),0,1),topics:(c.topics??[]).map((v:any)=>String(v).trim()).filter(Boolean).slice(0,8),entities:(c.entities??[]).map((v:any)=>String(v).trim()).filter(Boolean).slice(0,8),occurredAt:occurred(c.occurredAt),sourceIds:c.sourceIds,selected:true,locked:false,relationshipEvent:c.relationshipEvent?{kind:c.relationshipEvent.kind,importance:clamp(Math.round(c.relationshipEvent.importance),0,4),label:String(c.relationshipEvent.label??"").trim()}:undefined})};if(legacy.success&&typeof raw==="object"&&raw!==null&&"candidates" in raw)for(const c of legacy.data.candidates)add(c);else if(modern.success){if(includeSummary&&modern.data.summary){if(typeof modern.data.summary==="string")add({kind:"summary",content:modern.data.summary,importance:5,confidence:.8,valence:.5,arousal:.2});else add({...modern.data.summary,kind:"summary"})}for(const c of modern.data.memories)add(c)}return output}
export function transcript(messages:Message[],characters:Character[],userName="我"){return messages.filter(m=>m.status==="complete"&&(m.content.trim()||m.attachments?.some(item=>item.type==="text-image"))).map(m=>{const textImage=m.attachments?.find(item=>item.type==="text-image");return`${new Date(m.createdAt).toLocaleString("zh-CN")} · ${m.senderType==="user"?userName:characters.find(c=>c.id===m.senderId)?.name??"角色"}：${m.content}${textImage?.type==="text-image"?` [文字图片：${textImage.description}]`:""}`}).join("\n")}
async function sourceFor(character:Character,source:"chat"|"feed",conversationId?:string,limit=100){const key=cursorKey(character.id,source,conversationId);if(source==="feed")return{key,items:[] as SourceItem[]};const cursor=await db.memoryExtractionCursors.get(key);if(!conversationId)return{key,items:[] as SourceItem[]};const messages=(await db.messages.where("conversationId").equals(conversationId).sortBy("createdAt")).filter(m=>m.status==="complete"&&(m.content.trim()||m.attachments?.some(item=>item.type==="text-image"))),chars=await db.characters.toArray(),all=messages.map(m=>({id:m.id,text:transcript([m],chars)})),index=cursor?.lastSourceId?all.findIndex(item=>item.id===cursor.lastSourceId):-1;return{key,items:all.slice(index>=0?index+1:0,index>=0?index+1+limit:limit)}}
export async function pendingCount(character:Character,source:"chat"|"feed",conversationId?:string){if(!memoryExtractionSettingsOf(character).enabled)return 0;return(await sourceFor(character,source,conversationId,Number.MAX_SAFE_INTEGER)).items.length}
async function saveCandidate(batch:Pick<MemoryExtractionBatch,"characterId"|"conversationId"|"source"|"sourceIds">,candidate:MemoryCandidate,sourceSnapshot:string){const t=now(),memory:Memory={id:uid(),schemaVersion:SCHEMA_VERSION,createdAt:t,updatedAt:t,characterId:batch.characterId,conversationId:batch.conversationId,kind:candidate.kind,title:candidate.title,content:candidate.content.trim(),meaning:candidate.meaning,source:batch.source==="meet"?"AI 见面提炼":"AI 聊天提炼",sourceType:batch.source==="meet"?"meet":"chat",sourceIds:candidate.sourceIds?.length?candidate.sourceIds:batch.sourceIds,sourceSnapshot,occurredAt:candidate.occurredAt,topics:candidate.topics,entities:candidate.entities,importance:candidate.importance,confidence:candidate.confidence,valence:candidate.valence,arousal:candidate.arousal,activationCount:0,reinforcementCount:0,state:"active",locked:candidate.locked,digested:candidate.kind==="summary",contentHash:memoryContentHash(candidate.content)};await db.memories.add(memory);if(candidate.kind==="relationship"&&candidate.relationshipEvent){const current=await db.characters.get(batch.characterId);if(current){const next=applyRelationship(current,candidate.relationshipEvent);await db.characters.update(current.id,{relationship:next.relationship,updatedAt:t})}}return memory}
async function processCandidates(input:{character:Character;conversationId?:string;source:"chat"|"meet";sourceIds:string[];cursorKey:string;text:string;candidates:MemoryCandidate[];model:string}){const existing=(await db.memories.where("characterId").equals(input.character.id).toArray()).map(normalizedMemory),review:MemoryCandidate[]=[];let autoSavedCount=0;for(const candidate of input.candidates){const duplicate=existing.find(memory=>memory.kind===candidate.kind&&similarMemory(memory.content,candidate.content));if(duplicate&&(candidate.kind==="fact"||candidate.kind==="relationship")){await db.memories.update(duplicate.id,{reinforcementCount:(duplicate.reinforcementCount??0)+1,sourceIds:[...new Set([...(duplicate.sourceIds??[]),...input.sourceIds])],importance:Math.max(duplicate.importance,candidate.importance),state:"active",updatedAt:now()});autoSavedCount++;continue}const conflict=existing.find(memory=>memory.kind===candidate.kind&&lexicalMemorySimilarity(memory.content,candidate.content)>=.35&&!similarMemory(memory.content,candidate.content));if(conflict){review.push({...candidate,conflictWith:conflict.id,reviewReason:"可能与已有记忆冲突"});continue}if(memoryExtractionSettingsOf(input.character).autoSaveHighConfidence&&(candidate.confidence??0)>=.78){await saveCandidate({characterId:input.character.id,conversationId:input.conversationId,source:input.source,sourceIds:input.sourceIds},candidate,input.text);autoSavedCount++;continue}review.push({...candidate,reviewReason:(candidate.confidence??0)<.78?"置信度低于 0.78":"需要用户确认"})}const t=now(),batch:MemoryExtractionBatch={id:uid(),schemaVersion:SCHEMA_VERSION,createdAt:t,updatedAt:t,characterId:input.character.id,conversationId:input.conversationId,source:input.source,sourceIds:input.sourceIds,cursorKey:input.cursorKey,status:review.length?"pending":"confirmed",candidates:review,model:input.model,autoSavedCount};await db.memoryExtractionBatches.add(batch);if(!review.length)await db.memoryExtractionCursors.put({key:input.cursorKey,lastSourceId:input.sourceIds.at(-1),updatedAt:t});return batch}
async function generateCandidates(provider:ProviderSettings,character:Character,text:string,maxMemories:number,includeSummary:boolean){const summaryRule=includeSummary?"生成最多 1 条阶段摘要。":"summary 返回空字符串。",prompt=`请从内容中为角色“${character.name}”提炼长期记忆。只能按该角色能够知道或观察到的内容记录，不要把其他人的想法归给角色。\n核心设定：${coreSettingOf(character)}\n人物设定：${personaOf(character)}\n内容：\n${text}\n\n返回严格 JSON：{"summary":{"title":"阶段标题","content":"摘要","meaning":"意义","importance":1,"confidence":0.8,"valence":0.5,"arousal":0.2,"topics":[],"entities":[],"occurredAt":"ISO 时间"},"memories":[{"kind":"fact|plot|relationship","title":"标题","content":"记忆","meaning":"为何重要","importance":1,"confidence":0.8,"valence":0.5,"arousal":0.2,"topics":[],"entities":[],"occurredAt":"ISO 时间","relationshipEvent":{"kind":"positive|negative|neutral","importance":1,"label":"事件"}}]}。${summaryRule} 长期记忆最多 ${maxMemories} 条，importance 为 1–10，confidence/valence/arousal 为 0–1，不要编造。`;try{const raw=await new OpenAIProvider(provider).chat([{role:"system",content:"你是茶茶机本地海马体记忆整理器，只输出严格 JSON。"},{role:"user",content:prompt}],{stream:false});return validateMemoryCandidates(JSON.parse(clean(raw)),maxMemories,includeSummary)}catch(error){throw error instanceof ProviderError?error:new ProviderError("format","模型没有返回有效 JSON")}}
export async function createExtractionBatch(provider:ProviderSettings,character:Character,source:"chat"|"feed",conversationId?:string,options?:{limit?:number;maxMemories?:number;includeSummary?:boolean}){if(source==="feed")throw new ProviderError("format","动态内容不参与记忆整理");const settings=memoryExtractionSettingsOf(character);if(!settings.enabled)throw new ProviderError("format","海马体记忆已关闭");const limit=clamp(Math.trunc(options?.limit??settings.chatThreshold),1,200),maxMemories=clamp(Math.trunc(options?.maxMemories??settings.maxMemoriesPerBatch),1,12),includeSummary=options?.includeSummary??settings.includeSummary,{key,items}=await sourceFor(character,"chat",conversationId,limit);if(!items.length)throw new ProviderError("format","没有可整理的新内容");const existingBatch=await db.memoryExtractionBatches.where("cursorKey").equals(key).filter(batch=>batch.status==="pending").first();if(existingBatch)return existingBatch;const text=items.map(item=>item.text).join("\n"),candidates=await generateCandidates(provider,character,text,maxMemories,includeSummary);return processCandidates({character,conversationId,source:"chat",sourceIds:items.map(item=>item.id),cursorKey:key,text,candidates,model:provider.model})}
export async function createMeetExtractionBatch(provider:ProviderSettings,character:Character,session:MeetSession){const settings=memoryExtractionSettingsOf(character);if(!settings.enabled||!settings.meetMemoryEnabled)throw new ProviderError("format","见面记忆未开启");const key=cursorKey(character.id,"meet",session.id),existing=await db.memoryExtractionBatches.where("cursorKey").equals(key).first();if(existing)return existing;const text=[`场景：${session.scene.location??""} ${session.scene.atmosphere??""}`,session.summary?`总结：${session.summary}`:"",...session.entries.map(entry=>{if(entry.senderType==="user")return`用户：${entry.content??""}`;if(entry.senderType==="system")return`环境：${entry.narration??entry.content??""}`;return`${entry.senderId===character.id?character.name:"其他角色"}：${[entry.prose,entry.action,entry.dialogue,entry.senderId===character.id?entry.thought:undefined].filter(Boolean).join(" ")}`})].filter(Boolean).join("\n");const candidates=await generateCandidates(provider,character,text,settings.maxMemoriesPerBatch,settings.includeSummary);return processCandidates({character,conversationId:session.conversationId,source:"meet",sourceIds:session.entries.map(entry=>entry.id),cursorKey:key,text,candidates,model:provider.model})}
export async function confirmBatch(batchId:string,candidates:MemoryCandidate[]){const batch=await db.memoryExtractionBatches.get(batchId);if(!batch||batch.status!=="pending"||batch.source==="feed")return;const t=now();await db.transaction("rw",[db.memories,db.characters,db.memoryExtractionBatches,db.memoryExtractionCursors],async()=>{for(const raw of candidates.filter(item=>item.selected&&item.content.trim())){const candidate={...raw,confidence:raw.confidence??.7,valence:raw.valence??.5,arousal:raw.arousal??.2,topics:raw.topics??[],entities:raw.entities??[],occurredAt:raw.occurredAt??t};await saveCandidate(batch,candidate,batch.sourceIds.join("、"))}await db.memoryExtractionBatches.update(batch.id,{status:"confirmed",candidates,updatedAt:t});await db.memoryExtractionCursors.put({key:batch.cursorKey,lastSourceId:batch.sourceIds.at(-1),updatedAt:t})})}
export async function discardBatch(batchId:string){const batch=await db.memoryExtractionBatches.get(batchId);if(!batch||batch.status!=="pending"||batch.source==="feed")return;const t=now();await db.transaction("rw",[db.memoryExtractionBatches,db.memoryExtractionCursors],async()=>{await db.memoryExtractionBatches.update(batch.id,{status:"discarded",updatedAt:t});await db.memoryExtractionCursors.put({key:batch.cursorKey,lastSourceId:batch.sourceIds.at(-1),updatedAt:t})})}
let autoExtractionRun:Promise<void>|undefined;
async function runAutoExtraction(provider:ProviderSettings){if(!provider.apiKey)return;const summaryProvider=await resolveSecondaryProvider(provider),[characters,conversations]=await Promise.all([db.characters.toArray(),db.conversations.toArray()]);for(const character of characters){const settings=memoryExtractionSettingsOf(character);if(!canCharacterInteract(character)||!settings.enabled||settings.mode!=="auto")continue;for(const conversation of conversations.filter(item=>item.memberIds.includes(character.id)))if(await pendingCount(character,"chat",conversation.id)>=settings.chatThreshold)try{await createExtractionBatch(summaryProvider,character,"chat",conversation.id,{limit:settings.chatThreshold,maxMemories:settings.maxMemoriesPerBatch,includeSummary:settings.includeSummary})}catch{}}}
export function autoExtract(provider:ProviderSettings){if(autoExtractionRun)return autoExtractionRun;autoExtractionRun=runAutoExtraction(provider).finally(()=>{autoExtractionRun=undefined});return autoExtractionRun}
