import { appAssetPath } from "./publicDemo";
import {completeBackgroundTask,enqueueBackgroundTask,failBackgroundTask} from "./backgroundTasks";
import {db,getAppSettings} from "./db";
import {backgroundActivitySettingsOf,conversationNotificationSettingsOf,notificationSettingsOf} from "./notificationSettings";
import {now,type Character,type Conversation,type Message} from "./types";

export interface TeaNotificationPayload{title:string;body:string;tag:string;url:string;icon?:string;eventId:string;kind:"message"|"call"|"test";createdAt:number}

export async function registerTeaServiceWorker(){if(typeof navigator==="undefined"||!("serviceWorker" in navigator))return;try{const registration=await navigator.serviceWorker.register(appAssetPath("sw.js"), { scope: appAssetPath("") }),background=backgroundActivitySettingsOf(await getAppSettings());if(background.enabled&&background.modes?.length&&"sync" in registration)try{await (registration as ServiceWorkerRegistration&{sync:{register(tag:string):Promise<void>}}).sync.register("chacha-background")}catch{}return registration}catch{return}}
export function notificationSupported(){return typeof window!=="undefined"&&"Notification" in window&&"serviceWorker" in navigator}
export async function requestTeaNotificationPermission(){if(!notificationSupported())return"denied" as NotificationPermission;return Notification.requestPermission()}
async function showNotification(payload:TeaNotificationPayload){if(!notificationSupported()||Notification.permission!=="granted")throw new Error("系统通知权限未开启");await registerTeaServiceWorker();const registration=await navigator.serviceWorker.ready;await registration.showNotification(payload.title,{body:payload.body,icon:payload.icon||appAssetPath("icon-192-v2.png"),badge:appAssetPath("icon-192-v2.png"),tag:payload.tag,data:{url:payload.url,eventId:payload.eventId,kind:payload.kind}})}
export async function deliverNotification(payload:TeaNotificationPayload){const task=await enqueueBackgroundTask({type:"notification",entityId:payload.eventId,eventId:`notification:${payload.eventId}`,scheduledAt:payload.createdAt,payload});try{await showNotification(payload);await completeBackgroundTask(task.id);return true}catch(error){await failBackgroundTask(task.id,error,5*60*1000);return false}}
function currentConversationId(){if(typeof location==="undefined")return"";return location.pathname.match(/^\/messages\/([^/]+)$/)?.[1]??""}
function emitInApp(payload:TeaNotificationPayload){if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent("mira:in-app-notification",{detail:payload}))}
export async function notifyProactiveMessages(character:Character,conversation:Conversation,rows:Message[]){if(!rows.length)return;const app=await getAppSettings(),global=notificationSettingsOf(app),local=conversationNotificationSettingsOf(conversation);if(!global.enabled||!global.proactiveMessages||!local.messages)return;const latest=rows.at(-1)!,showPreview=local.previewContent==="show"||(local.previewContent==="inherit"&&global.previewContent),textImage=latest.attachments?.find(item=>item.type==="text-image"),preview=latest.content||(textImage?.type==="text-image"?`[文字图片] ${textImage.description}`:"发来一条新消息"),payload:TeaNotificationPayload={title:character.name,body:showPreview?preview:"发来一条新消息",tag:`chat-${conversation.id}`,url:`/messages/${conversation.id}?message=${latest.id}`,icon:character.avatar||undefined,eventId:latest.proactiveEventId||latest.id,kind:"message",createdAt:latest.createdAt};if(document.visibilityState==="visible"){if(currentConversationId()!==conversation.id)emitInApp(payload);return}await deliverNotification(payload)}
export async function notifyChatReplyCompleted(character:Character,conversation:Conversation,message:Message){const app=await getAppSettings(),global=notificationSettingsOf(app),local=conversationNotificationSettingsOf(conversation);if(!global.enabled||!local.messages)return;const showPreview=local.previewContent==="show"||(local.previewContent==="inherit"&&global.previewContent),textImage=message.attachments?.find(item=>item.type==="text-image"),preview=message.content||(textImage?.type==="text-image"?"[\u6587\u5b57\u56fe\u7247] "+textImage.description:"\u53d1\u6765\u4e00\u6761\u65b0\u6d88\u606f"),payload:TeaNotificationPayload={title:character.name,body:showPreview?preview:"\u53d1\u6765\u4e00\u6761\u65b0\u6d88\u606f",tag:"chat-"+conversation.id,url:"/messages/"+conversation.id+"?message="+message.id,icon:character.avatar||undefined,eventId:message.id,kind:"message",createdAt:message.createdAt};if(typeof document!=="undefined"&&document.visibilityState==="visible"){if(currentConversationId()!==conversation.id)emitInApp(payload);return}await deliverNotification(payload)}
export async function notifyIncomingCall(character:Character,conversation:Conversation,input:{eventId:string;callType:"voice"|"video";summary:string;createdAt:number}){const app=await getAppSettings(),global=notificationSettingsOf(app),local=conversationNotificationSettingsOf(conversation);if(!global.enabled||!global.incomingCalls||!local.calls)return false;const showPreview=local.previewContent==="show"||(local.previewContent==="inherit"&&global.previewContent),label=input.callType==="video"?"视频通话":"语音通话",payload:TeaNotificationPayload={title:character.name,body:showPreview?`${label} · ${input.summary}`:`发来${label}`,tag:`call-${conversation.id}`,url:`/messages/${conversation.id}?incomingCall=${input.eventId}`,icon:character.avatar||undefined,eventId:input.eventId,kind:"call",createdAt:input.createdAt};if(document.visibilityState==="visible"){emitInApp(payload);return false}return deliverNotification(payload)}
export async function sendTestNotification(){const payload:TeaNotificationPayload={title:"茶茶机",body:"通知设置成功，角色消息会显示在这里。",tag:"chacha-test",url:"/settings",eventId:`test-${now()}`,kind:"test",createdAt:now()};return deliverNotification(payload)}
export async function retryPendingNotificationTasks(){const tasks=await db.backgroundTasks.where("type").equals("notification").filter(task=>task.state==="failed"&&task.nextAttemptAt<=now()).toArray();for(const task of tasks){const payload=task.payload as TeaNotificationPayload;if(now()-payload.createdAt>5*60*1000){await completeBackgroundTask(task.id);continue}try{await showNotification(payload);await completeBackgroundTask(task.id)}catch(error){await failBackgroundTask(task.id,error,5*60*1000)}}}