import {beforeEach,describe,expect,it,vi} from "vitest";
import {db} from "./db";
import {maybeIntroducePhoneContact,phoneContactDuplicate,phoneNewContactProbability,stablePhoneEventRoll} from "./phoneContactsEvolution";
import {buildPhoneSearchResults,recordRecentPhoneApp,removeRecentPhoneApp,savePhoneSearchQuery} from "./phoneNavigation";
import {normalizeEnhancedPhoneState} from "./phoneEcosystemEnhancements";
import {defaultProvider,type Character,type CharacterPhoneState,type PhoneContact} from "./types";

const character:Character={id:"c",schemaVersion:1,createdAt:1,updatedAt:1,name:"月白",avatar:"",bio:"旅人",personality:"安静",speakingStyle:"简洁",background:"来自旧城",language:"中文",coreSetting:"来自旧城的旅人",persona:"警惕，有自己的社交圈",chatSettings:{language:"中文",contextLimit:30,stream:false,strategyMode:{enabled:false}},proactive:{messages:false,timeAware:false,frequency:"medium",quietStart:"23:00",quietEnd:"08:00",catchupLimit:3,dailyLimit:10},relationship:{intimacy:20,trust:30,mood:"平静",recentEvents:[]},lastActiveAt:1};
const contact:PhoneContact={id:"p",name:"阿林",relationship:"朋友",persona:"熟悉月白",email:"alin@mail.local",characterKnowledge:[],createdAt:1,updatedAt:1};
const baseState=():CharacterPhoneState=>normalizeEnhancedPhoneState({id:"c",characterId:"c",schemaVersion:1,createdAt:1,updatedAt:1,initializedAt:1,lastSyncedAt:1,contacts:[structuredClone(contact)],talkThreads:[{id:"t",contactId:"p",messages:[{id:"tm",senderType:"contact",content:"明天在中央公园见。",createdAt:2}],updatedAt:2,unreadCount:0}],mail:{messages:[{id:"mail",threadId:"mt",folder:"inbox",fromContactId:"p",fromAddress:"alin@mail.local",toContactIds:[],toAddresses:["owner@mail.local"],subject:"会议安排",body:"下午三点开会。",createdAt:3,updatedAt:3}],unreadCount:1},maps:{savedPlaces:[{id:"place",name:"中央公园",category:"公园",description:"见面地点",relatedContactIds:["p"]}],recentVisits:[],searches:[]},files:{items:[{id:"private",name:"私人计划.txt",kind:"private",folder:"私人",content:"周末计划",updatedAt:4,hidden:false},{id:"hidden",name:"秘密.txt",kind:"hidden",folder:"隐藏",content:"绝对秘密",updatedAt:5,hidden:true}]},voiceMemos:[{id:"memo",title:"会议录音",transcript:"讨论项目进度",duration:"01:20",recordedAt:6,category:"meeting"}],reminders:[{id:"rem",title:"回复阿林",notes:"今晚处理",completed:false}],systemSettings:{accountName:"月白",accountEmail:"owner@mail.local",deviceName:"月白的手机",permissions:[],screenTime:[],screenTimeDate:"2026-08-04"},proactiveState:{generationEventIds:[],lastGeneratedAt:1},searchState:{recentQueries:[]},recentApps:[],appContents:{calls:{contacts:[{name:"阿林"}],records:[{contactName:"阿林",summary:"确认会议",details:"讨论项目进度",time:"2026-08-04 10:00",transcript:[]}]},calendar:{events:[{title:"项目会议",note:"下午三点",date:"2026-08-04",time:"15:00",category:"工作",generationEventId:"cal"}]},browser:{history:[{query:"中央公园路线",title:"地图结果",visitedAt:"2026-08-04"}]}},timeline:[],operationTraces:[]},character);
const provider={...defaultProvider, networkMode: "direct" as const,apiKey:"test",stream:false};

beforeEach(async()=>{await db.delete();await db.open();await db.characters.add(structuredClone(character));await db.characterPhoneStates.add(baseState());vi.restoreAllMocks()});

describe("new phone contacts",()=>{
 it("uses stable rolls and clamps dynamic probability",()=>{expect(stablePhoneEventRoll("same-event")).toBe(stablePhoneEventRoll("same-event"));expect(phoneNewContactProbability({newEntityCount:0,sourceActivityCount:0})).toBe(.15);expect(phoneNewContactProbability({newEntityCount:1,sourceActivityCount:99})).toBe(.35)});
 it("deduplicates names, email and phone",()=>{const state=baseState();expect(phoneContactDuplicate(state,{name:" 阿 林 "})?.id).toBe("p");expect(phoneContactDuplicate(state,{name:"别人",email:"alin@mail.local"})?.id).toBe("p")});
 it("adds at most one persistent contact and first call for the same event",async()=>{let eventId="";for(let index=0;index<10000;index++){const candidate=`contact-event-${index}`;if(stablePhoneEventRoll(candidate)<.15){eventId=candidate;break}}const fetchMock=vi.fn(async()=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({name:"程老师",relationship:"旧城课程的老师",persona:"严格、直接，对月白的迟到一直有意见，不会无条件迁就他。",status:"最近重新联系",phone:"工作号码",email:"teacher@mail.local",characterKnowledge:["知道月白曾经上过自己的课"],firstAppearance:"call",callDirection:"incoming",callSummary:"确认旧资料",callDetails:"程老师打来电话询问旧资料是否还保留。"})}}]}),{status:200,headers:{"Content-Type":"application/json"}}));vi.stubGlobal("fetch",fetchMock);let state=await maybeIntroducePhoneContact({state:baseState(),character,provider,eventId,since:1,origin:"proactive"});state=await maybeIntroducePhoneContact({state,character,provider,eventId,since:1,origin:"proactive"});expect(state.contacts.filter(item=>item.name==="程老师")).toHaveLength(1);expect((state.appContents.calls as any).records.some((item:any)=>item.contactName==="程老师")).toBe(true);expect(fetchMock).toHaveBeenCalledTimes(1)});
 it("stops adding contacts at forty",async()=>{const state=baseState();state.contacts=Array.from({length:40},(_,index)=>({...contact,id:`p${index}`,name:`联系人${index}`,email:`p${index}@mail.local`}));const fetchMock=vi.fn();vi.stubGlobal("fetch",fetchMock);const next=await maybeIntroducePhoneContact({state,character,provider,eventId:"limit",since:0,origin:"plot"});expect(next.contacts).toHaveLength(40);expect(fetchMock).not.toHaveBeenCalled()})
});

describe("phone search and recent apps",()=>{
 it("searches across apps, includes private files and excludes hidden files",()=>{const state=baseState();expect(buildPhoneSearchResults(state,"中央公园").some(item=>item.appId==="messages")).toBe(true);expect(buildPhoneSearchResults(state,"私人计划").some(item=>item.targetId==="private")).toBe(true);expect(buildPhoneSearchResults(state,"绝对秘密")).toEqual([]);expect(buildPhoneSearchResults(state,"项目").some(item=>item.appId==="mail"||item.appId==="calendar")).toBe(true)});
 it("deduplicates recent queries and caps them at twenty",async()=>{for(let index=0;index<22;index++)await savePhoneSearchQuery("c",`查询${index}`);await savePhoneSearchQuery("c","查询10");const state=await db.characterPhoneStates.get("c");expect(state?.searchState?.recentQueries).toHaveLength(20);expect(state?.searchState?.recentQueries[0].query).toBe("查询10")});
 it("keeps six distinct recent apps and removes cards without deleting content",async()=>{for(const appId of ["messages","mail","files","voice-memos","notes","maps","contacts"] as const)await recordRecentPhoneApp("c",appId,appId==="messages"?"p":undefined);let state=await db.characterPhoneStates.get("c");expect(state?.recentApps).toHaveLength(6);expect(new Set(state?.recentApps?.map(item=>item.appId)).size).toBe(6);const contactsBefore=state?.contacts.length;state=await removeRecentPhoneApp("c","mail");expect(state?.recentApps?.some(item=>item.appId==="mail")).toBe(false);expect(state?.contacts.length).toBe(contactsBefore)})
});
