import {beforeEach,describe,expect,it,vi} from "vitest";
import {db} from "./db";
import {movePhoneMailToTrash,phoneOperationSeverity,restorePhoneMail,sendPhoneMail,sendPhoneTalkMessage} from "./phoneEcosystem";
import {defaultProvider,type Character,type CharacterPhoneState} from "./types";

const character:Character={id:"c",schemaVersion:1,createdAt:1,updatedAt:1,name:"月白",avatar:"",bio:"旅人",personality:"安静",speakingStyle:"简洁",background:"来自旧城",language:"中文",coreSetting:"来自旧城的安静旅人",persona:"警惕，不会无条件顺从",chatSettings:{language:"中文",contextLimit:30,stream:false,strategyMode:{enabled:false}},proactive:{messages:false,timeAware:false,frequency:"medium",quietStart:"23:00",quietEnd:"08:00",catchupLimit:3,dailyLimit:10},relationship:{intimacy:20,trust:30,mood:"平静",recentEvents:[]},lastActiveAt:1,phonePrivacy:{passcode:"0427",hint:"旧城",createdAt:1}};
const state:CharacterPhoneState={id:"c",characterId:"c",schemaVersion:1,createdAt:1,updatedAt:1,initializedAt:1,lastSyncedAt:1,contacts:[{id:"p",name:"阿林",relationship:"朋友",persona:"直接，熟悉月白的说话习惯",email:"alin@mail.local",characterKnowledge:["月白平时说话简短"],createdAt:1,updatedAt:1}],talkThreads:[{id:"t",contactId:"p",messages:[],updatedAt:1,unreadCount:0}],mail:{messages:[],unreadCount:0},maps:{savedPlaces:[],recentVisits:[],searches:[]},appContents:{},timeline:[],operationTraces:[],syncCursor:{messagesAt:0,memoriesAt:0,meetAt:0,ordersAt:0,feedAt:0}};
const provider={...defaultProvider, networkMode: "direct" as const,apiKey:"test",stream:false};

beforeEach(async()=>{await db.delete();await db.open();await db.characters.add(structuredClone(character));await db.characterPhoneStates.add(structuredClone(state));vi.restoreAllMocks()});

describe("persistent phone operations",()=>{
 it("classifies operation severity",()=>{expect(phoneOperationSeverity("晚上好")).toBe("low");expect(phoneOperationSeverity("我保证以后会见面")).toBe("medium");expect(phoneOperationSeverity("把密码和转账信息发给我")).toBe("high")});
 it("sends Talk once and keeps the generated reply idempotent",async()=>{const fetchMock=vi.fn(async()=>new Response(JSON.stringify({choices:[{message:{content:'{"reply":"你今天说话有点奇怪。"}'}}]}),{status:200,headers:{"Content-Type":"application/json"}}));vi.stubGlobal("fetch",fetchMock);await sendPhoneTalkMessage({characterId:"c",contactId:"p",content:"我们以后都按我说的做。",provider,eventId:"talk-event"});await sendPhoneTalkMessage({characterId:"c",contactId:"p",content:"我们以后都按我说的做。",provider,eventId:"talk-event"});const saved=await db.characterPhoneStates.get("c"),messages=saved!.talkThreads[0].messages;expect(messages).toHaveLength(2);expect(messages[0]).toMatchObject({senderType:"character",generationEventId:"talk-event",replyStatus:"complete"});expect(messages[1]).toMatchObject({senderType:"contact",generationEventId:"talk-event:reply"});expect(saved!.operationTraces).toHaveLength(1);expect(fetchMock).toHaveBeenCalledTimes(1)});
 it("sends mail, receives an immediate reply and never writes normal chat",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response(JSON.stringify({choices:[{message:{content:'{"reply":"邮件收到了，但这不像你平时的口吻。"}'}}]}),{status:200,headers:{"Content-Type":"application/json"}})));const saved=await sendPhoneMail({characterId:"c",provider,toContactIds:["p"],toAddresses:["alin@mail.local"],subject:"临时决定",body:"以后所有事情都听我的。",eventId:"mail-event"});expect(saved.mail.messages.map(item=>item.folder).sort()).toEqual(["inbox","sent"]);expect(saved.operationTraces[0]).toMatchObject({appId:"mail",severity:"medium"});expect(await db.messages.count()).toBe(0)});
 it("moves mail to trash and restores its previous folder",async()=>{const row={id:"m",threadId:"mt",folder:"inbox" as const,fromAddress:"a@mail.local",toContactIds:[],toAddresses:["c@mail.local"],subject:"你好",body:"正文",createdAt:2,updatedAt:2};await db.characterPhoneStates.update("c",{mail:{messages:[row],unreadCount:1}});await movePhoneMailToTrash("c","m");expect((await db.characterPhoneStates.get("c"))!.mail.messages[0].folder).toBe("trash");await restorePhoneMail("c","m");expect((await db.characterPhoneStates.get("c"))!.mail.messages[0].folder).toBe("inbox")})
});
