import {beforeEach,describe,expect,it,vi} from "vitest";
import {db} from "./db";
import {maybeGenerateProactivePhoneActivity,normalizeEnhancedPhoneState,sendEnhancedMail,sendEnhancedTalkMessage,togglePhoneReminder} from "./phoneEcosystemEnhancements";
import {defaultProvider,type Character,type CharacterPhoneState} from "./types";

const character:Character={id:"c",schemaVersion:1,createdAt:1,updatedAt:1,name:"月白",avatar:"",bio:"旅人",personality:"安静",speakingStyle:"简洁",background:"来自旧城",language:"中文",coreSetting:"来自旧城的安静旅人",persona:"警惕，有自己的安排",chatSettings:{language:"中文",contextLimit:30,stream:false,strategyMode:{enabled:false}},proactive:{messages:false,timeAware:false,frequency:"medium",quietStart:"23:00",quietEnd:"08:00",catchupLimit:3,dailyLimit:10},relationship:{intimacy:20,trust:30,mood:"平静",recentEvents:[]},lastActiveAt:1,phonePrivacy:{passcode:"0427",hint:"旧城",createdAt:1}};
const baseState:CharacterPhoneState={id:"c",characterId:"c",schemaVersion:1,createdAt:1,updatedAt:1,initializedAt:1,lastSyncedAt:1,contacts:[{id:"p",name:"阿林",relationship:"朋友",persona:"直接，熟悉月白",email:"alin@mail.local",characterKnowledge:[],createdAt:1,updatedAt:1}],talkThreads:[{id:"t",contactId:"p",messages:[],updatedAt:1,unreadCount:0}],mail:{messages:[],unreadCount:0},maps:{savedPlaces:[],recentVisits:[],searches:[]},appContents:{},timeline:[],operationTraces:[],syncCursor:{messagesAt:0,memoriesAt:0,meetAt:0,ordersAt:0,feedAt:0}};
const provider={...defaultProvider, networkMode: "direct" as const,apiKey:"test",stream:false};

beforeEach(async()=>{await db.delete();await db.open();await db.characters.add(structuredClone(character));await db.characterPhoneStates.add(structuredClone(baseState));vi.restoreAllMocks()});

describe("phone ecosystem expansion",()=>{
 it("lazily fills files, voice memos, reminders, system settings and unified calls",()=>{const state=normalizeEnhancedPhoneState(structuredClone(baseState),character);expect(state.files?.items.some(item=>item.kind==="hidden")).toBe(true);expect(state.voiceMemos?.length).toBeGreaterThan(0);expect(state.reminders?.length).toBeGreaterThan(0);expect(state.systemSettings?.permissions.length).toBeGreaterThan(0);expect((state.appContents.calls as any).contacts[0].name).toBe("阿林")});
 it("turns a mail appointment into a calendar event",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response(JSON.stringify({choices:[{message:{content:'{"reply":"可以，明天下午三点见。"}'}}]}),{status:200,headers:{"Content-Type":"application/json"}})));const state=await sendEnhancedMail({characterId:"c",provider,toContactIds:["p"],toAddresses:["alin@mail.local"],subject:"见面时间",body:"明天下午三点见面。",eventId:"mail-date"}),events=(state.appContents.calendar as any).events;expect(events).toHaveLength(1);expect(events[0]).toMatchObject({time:"15:00",category:"邮件约定",generationEventId:"mail-calendar:mail-date"});expect(events[0].date).toBe(new Date(Date.now()+86400000).toLocaleDateString("sv-SE"))});
 it("adds a Talk meeting place to Maps once",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response(JSON.stringify({choices:[{message:{content:'{"reply":"好，在中央公园东门等你。"}'}}]}),{status:200,headers:{"Content-Type":"application/json"}})));await sendEnhancedTalkMessage({characterId:"c",contactId:"p",content:"明天下午在中央公园见面。",provider,eventId:"talk-place"});const state=await sendEnhancedTalkMessage({characterId:"c",contactId:"p",content:"明天下午在中央公园见面。",provider,eventId:"talk-place"});expect(state.maps.searches.filter(item=>item.id==="talk-map:talk-place")).toHaveLength(1);expect(state.maps.savedPlaces.some(item=>item.name.includes("中央公园"))).toBe(true)});
 it("lets plot-aware proactive activity add calls, files and reminders idempotently",async()=>{const state=normalizeEnhancedPhoneState(structuredClone(baseState),character);const eventRoot=`phone-proactive:c:${Math.floor(Date.now()/(2*3600000))}`;state.proactiveState={lastGeneratedAt:0,generationEventIds:[`contact-roll:${eventRoot}`]};await db.characterPhoneStates.put(state);const fetchMock=vi.fn(async()=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({actions:[{type:"call",contactName:"阿林",direction:"incoming",summary:"确认明天见面的地点",details:"阿林来电确认中央公园东门。"},{type:"file",name:"见面路线.txt",kind:"download",folder:"下载",content:"中央公园东门路线"},{type:"reminder",title:"明天去中央公园",notes:"提前十分钟出门",completed:false}]})}}]}),{status:200,headers:{"Content-Type":"application/json"}}));vi.stubGlobal("fetch",fetchMock);const first=await maybeGenerateProactivePhoneActivity("c",provider),second=await maybeGenerateProactivePhoneActivity("c",provider);expect((first.appContents.calls as any).records.some((item:any)=>item.summary.includes("见面"))).toBe(true);expect(first.files?.items.some(item=>item.name==="见面路线.txt")).toBe(true);expect(first.reminders?.some(item=>item.title==="明天去中央公园")).toBe(true);expect(second.files?.items.filter(item=>item.name==="见面路线.txt")).toHaveLength(1);expect(fetchMock).toHaveBeenCalledTimes(1)});
 it("persists reminder completion and leaves an operation trace",async()=>{const state=normalizeEnhancedPhoneState(structuredClone(baseState),character);await db.characterPhoneStates.put(state);const id=state.reminders![0].id,next=await togglePhoneReminder("c",id,true);expect(next?.reminders?.find(item=>item.id===id)?.completed).toBe(true);expect(next?.operationTraces.some(item=>item.appId==="notes"&&item.action==="toggle")).toBe(true)})
});
