import {getSetting,setSetting} from "./db";
import {defaultProvider,now,uid,type Conversation,type ProviderPreset,type ProviderPresetState,type ProviderSettings} from "./types";

export const PROVIDER_PRESETS_KEY="provider-presets-v1";
export const emptyProviderPresetState=():ProviderPresetState=>({version:1,items:[]});
function normalizeProvider(provider:ProviderSettings):ProviderSettings{return{...defaultProvider,...provider,networkMode:provider.networkMode==="relay"&&provider.networkModeExplicit===true?"relay":"direct",networkModeExplicit:provider.networkModeExplicit===true,baseUrl:provider.baseUrl.trim(),apiKey:provider.apiKey.trim(),model:provider.model.trim(),temperature:Math.max(0,Math.min(2,Number(provider.temperature)||0)),maxTokens:Math.max(1,Math.trunc(Number(provider.maxTokens)||defaultProvider.maxTokens)),contextLimit:Math.max(2,Math.min(100,Math.trunc(Number(provider.contextLimit)||defaultProvider.contextLimit))),contextBudgetMode:(provider.contextBudgetMode==="custom"?"custom":"auto") as "auto" | "custom",contextWindowTokens:Math.max(8_000,Math.min(1_000_000,Math.trunc(Number(provider.contextWindowTokens??defaultProvider.contextWindowTokens??128_000)))),timeoutMs:Math.max(1000,Math.trunc(Number(provider.timeoutMs)||defaultProvider.timeoutMs))}}
export function normalizeProviderPresetState(value:unknown):ProviderPresetState{const raw=value as Partial<ProviderPresetState>|undefined,items=Array.isArray(raw?.items)?raw!.items.filter((item):item is ProviderPreset=>Boolean(item&&typeof item.id==="string"&&typeof item.name==="string"&&item.provider)).map(item=>({...item,name:item.name.trim().slice(0,40)||"未命名预设",provider:normalizeProvider(item.provider),createdAt:Number(item.createdAt)||now(),updatedAt:Number(item.updatedAt)||Number(item.createdAt)||now()})):[];const activeId=items.some(item=>item.id===raw?.activeId)?raw?.activeId:undefined;return{version:1,activeId,items:items.sort((a,b)=>b.updatedAt-a.updatedAt)}}
export async function getProviderPresetState(){return normalizeProviderPresetState(await getSetting<unknown>(PROVIDER_PRESETS_KEY,emptyProviderPresetState()))}
export async function saveProviderPreset(input:{id?:string;name:string;provider:ProviderSettings;activate?:boolean}){const name=input.name.trim().slice(0,40);if(!name)throw new Error("请输入预设名称");const provider=normalizeProvider(input.provider);if(!provider.baseUrl||!provider.apiKey||!provider.model)throw new Error("请先填写 Base URL、API Key 和模型名称");const state=await getProviderPresetState(),time=now(),existing=input.id?state.items.find(item=>item.id===input.id):undefined,preset:ProviderPreset=existing?{...existing,name,provider,updatedAt:time}:{id:uid(),name,provider,createdAt:time,updatedAt:time},items=[preset,...state.items.filter(item=>item.id!==preset.id)],next:ProviderPresetState={version:1,activeId:input.activate===false?state.activeId:preset.id,items};await setSetting(PROVIDER_PRESETS_KEY,next);if(input.activate!==false)await setSetting("provider",provider);return{state:next,preset}}
export async function activateProviderPreset(id:string){const state=await getProviderPresetState(),preset=state.items.find(item=>item.id===id);if(!preset)throw new Error("预设不存在或已删除");const next={...state,activeId:preset.id};await setSetting(PROVIDER_PRESETS_KEY,next);await setSetting("provider",preset.provider);return{state:next,preset}}
export async function deleteProviderPreset(id:string){const state=await getProviderPresetState(),next:ProviderPresetState={version:1,activeId:state.activeId===id?undefined:state.activeId,items:state.items.filter(item=>item.id!==id)};await setSetting(PROVIDER_PRESETS_KEY,next);return next}
export async function deactivateProviderPreset(){const state=await getProviderPresetState(),next={...state,activeId:undefined};await setSetting(PROVIDER_PRESETS_KEY,next);return next}
export async function clearProviderPresetKeys(){const state=await getProviderPresetState(),time=now(),next:ProviderPresetState={...state,items:state.items.map(item=>({...item,provider:{...item.provider,apiKey:""},updatedAt:time}))};await setSetting(PROVIDER_PRESETS_KEY,next);return next}
export async function resolveConversationProvider(conversation:Conversation,globalProvider:ProviderSettings,presetIdOverride?:string){const requestedId=(presetIdOverride??conversation.chatSettings?.providerPresetId?.trim())||undefined;if(!requestedId)return{provider:normalizeProvider(globalProvider),presetId:undefined,preset:undefined,missing:false};const state=await getProviderPresetState(),preset=state.items.find(item=>item.id===requestedId);if(!preset)return{provider:normalizeProvider(globalProvider),presetId:requestedId,preset:undefined,missing:true};return{provider:preset.provider,presetId:preset.id,preset,missing:false}}
