import {beforeEach,describe,expect,it} from "vitest";
import {db,getProvider,setSetting} from "./db";
import {activateProviderPreset,clearProviderPresetKeys,deleteProviderPreset,getProviderPresetState,resolveConversationProvider,saveProviderPreset} from "./providerPresets";
import {defaultModelServiceSettings,defaultProvider,type Conversation} from "./types";
import {getModelServiceSettings,saveModelServiceSettings} from "./modelServices";

const provider=(model:string,key:string)=>({...defaultProvider, networkMode: "direct" as const,baseUrl:"https://example.com/v1",apiKey:key,model});
describe("provider presets",()=>{
 beforeEach(async()=>{await db.delete();await db.open()});
 it("normalizes legacy Relay settings to direct unless explicitly selected",async()=>{await setSetting("provider",{...defaultProvider,networkMode:"relay",networkModeExplicit:false});expect((await getProvider()).networkMode).toBe("direct");await setSetting("provider",{...defaultProvider,networkMode:"relay",networkModeExplicit:true});expect((await getProvider()).networkMode).toBe("relay")});
 it("saves multiple presets and switches the active provider",async()=>{const first=await saveProviderPreset({name:"快速",provider:provider("fast","key-a")}),second=await saveProviderPreset({name:"高质量",provider:provider("quality","key-b"),activate:false});expect(second.state.items).toHaveLength(2);expect(second.state.activeId).toBe(first.preset.id);const switched=await activateProviderPreset(second.preset.id);expect(switched.state.activeId).toBe(second.preset.id);expect((await getProvider()).model).toBe("quality")});
 it("updates a preset name without creating a duplicate",async()=>{const created=await saveProviderPreset({name:"旧名称",provider:provider("model","key")});const updated=await saveProviderPreset({id:created.preset.id,name:"新名称",provider:provider("model-2","key-2")});expect(updated.state.items).toHaveLength(1);expect(updated.preset).toMatchObject({name:"新名称",provider:{model:"model-2",apiKey:"key-2"}})});
 it("deletes presets and clears all locally stored API keys",async()=>{const created=await saveProviderPreset({name:"方案",provider:provider("model","secret")});let state=await clearProviderPresetKeys();expect(state.items[0].provider.apiKey).toBe("");state=await deleteProviderPreset(created.preset.id);expect(state.items).toEqual([]);expect((await getProviderPresetState()).activeId).toBeUndefined()});
 it("does not change secondary or vision services when switching main presets",async()=>{await saveModelServiceSettings({...defaultModelServiceSettings,secondary:{enabled:true,provider:provider("helper","secondary-key")}});const first=await saveProviderPreset({name:"主方案一",provider:provider("main-a","main-a-key")}),second=await saveProviderPreset({name:"主方案二",provider:provider("main-b","main-b-key"),activate:false});await activateProviderPreset(second.preset.id);expect((await getModelServiceSettings()).secondary.provider).toMatchObject({model:"helper",apiKey:"secondary-key"});expect(first.state.activeId).toBe(first.preset.id)});
 it("resolves a complete preset for one conversation without changing the global provider",async()=>{const global=provider("global","global-key");await setSetting("provider",global);const saved=await saveProviderPreset({name:"conversation",provider:{...provider("conversation-model","conversation-key"),baseUrl:"https://conversation.example/v1"},activate:false}),conversation={id:"conversation",chatSettings:{providerPresetId:saved.preset.id}} as Conversation,resolved=await resolveConversationProvider(conversation,global);expect(resolved.provider).toMatchObject({model:"conversation-model",apiKey:"conversation-key",baseUrl:"https://conversation.example/v1"});expect((await getProvider()).model).toBe("global")});
 it("falls back to global when a selected preset is missing",async()=>{const global=provider("global","global-key"),conversation={id:"conversation",chatSettings:{providerPresetId:"missing"}} as Conversation,resolved=await resolveConversationProvider(conversation,global);expect(resolved).toMatchObject({missing:true,presetId:"missing",provider:{model:"global"}})});
 it("treats an empty task override as an explicit global snapshot",async()=>{const global=provider("global","global-key"),saved=await saveProviderPreset({name:"conversation",provider:provider("conversation","conversation-key"),activate:false}),conversation={id:"conversation",chatSettings:{providerPresetId:saved.preset.id}} as Conversation,resolved=await resolveConversationProvider(conversation,global,"");expect(resolved.provider.model).toBe("global");expect(resolved.presetId).toBeUndefined()});

});