import {beforeEach,describe,expect,it,vi} from "vitest";
import {db} from "./db";
import {applyStrategyEvaluation,evaluateStrategyInteraction,saveConfessionMessages,validateConfessionMessages,validateStrategyEvaluation} from "./relationshipStrategy";
import {defaultProvider,SCHEMA_VERSION,type Character,type Conversation} from "./types";

const character=(overrides:Partial<Character>={}):Character=>({id:"c",schemaVersion:SCHEMA_VERSION,createdAt:1,updatedAt:1,name:"茶茶",avatar:"",bio:"",personality:"",speakingStyle:"",background:"",language:"中文",chatSettings:{language:"中文",contextLimit:30,stream:false,strategyMode:{enabled:true}},proactive:{messages:false,timeAware:false,frequency:"low",quietStart:"23:00",quietEnd:"08:00",catchupLimit:1,dailyLimit:1},relationship:{intimacy:10,trust:10,mood:"平静",recentEvents:[]},lastActiveAt:1,...overrides});
const conversation:Conversation={id:"v",schemaVersion:1,createdAt:1,updatedAt:1,title:"私聊",type:"private",memberIds:["c"],presetIds:[],loreBookIds:[],lastActivityAt:1};

describe("strategy relationship progression",()=>{
 beforeEach(async()=>{await db.delete();await db.open();vi.restoreAllMocks()});
 it("validates strict bounded evaluation output",()=>{expect(validateStrategyEvaluation({intimacyDelta:2,trustDelta:1,reason:"认真倾听"}).reason).toBe("认真倾听");expect(()=>validateStrategyEvaluation({intimacyDelta:5,trustDelta:0,reason:"过大"})).toThrow()});
 it("applies daily positive caps and records the source once",()=>{const first=applyStrategyEvaluation(character({relationship:{intimacy:10,trust:10,mood:"平静",recentEvents:[],dailyProgress:{date:new Date(1000).toLocaleDateString("en-CA"),intimacyGain:5,trustGain:3}}}),{intimacyDelta:3,trustDelta:3,reason:"持续尊重"},"m1",1000);expect(first.character.relationship.intimacy).toBe(11);expect(first.character.relationship.trust).toBe(11);expect(first.character.relationship.dailyProgress?.intimacyGain).toBe(6);expect(applyStrategyEvaluation(first.character,{intimacyDelta:3,trustDelta:3,reason:"重复"},"m1",1000).duplicate).toBe(true)});
 it("allows logical negative changes without positive caps",()=>{const result=applyStrategyEvaluation(character(),{intimacyDelta:-4,trustDelta:-3,reason:"明显越界"},"m2",1000);expect(result.character.relationship.intimacy).toBe(6);expect(result.character.relationship.trust).toBe(7);expect(result.character.relationship.recentEvents[0]).toContain("明显越界")});
 it("marks the first double-100 transition for confession",()=>{const result=applyStrategyEvaluation(character({relationship:{intimacy:99,trust:99,mood:"期待",recentEvents:[]}}),{intimacyDelta:1,trustDelta:1,reason:"真诚回应"},"m3",1000);expect(result.shouldConfess).toBe(true)});
 it("accepts naturally varied confession bubble counts and lengths",()=>{const messages=["我喜欢你","其实想了很久。","要不要……以后也让我陪着你？","不用现在回答我。"];expect(validateConfessionMessages({messages})).toEqual(messages);expect(validateConfessionMessages({messages:Array.from({length:15},(_,index)=>`消息${index}`)})).toHaveLength(12);expect(()=>validateConfessionMessages({messages:[]})).toThrow()});
 it("evaluates an enabled private interaction once",async()=>{const c=character();await db.characters.add(c);const fetchMock=vi.fn(async()=>new Response(JSON.stringify({choices:[{message:{content:'{"intimacyDelta":2,"trustDelta":1,"reason":"认真回应了角色"}'}}]}),{status:200,headers:{"Content-Type":"application/json"}}));vi.stubGlobal("fetch",fetchMock);const provider={...defaultProvider, networkMode: "direct" as const,apiKey:"test"},first=await evaluateStrategyInteraction({character:c,sourceId:"m1",userText:"我记得你说过的话",messages:[],characters:[c],provider}),second=await evaluateStrategyInteraction({character:first.character,sourceId:"m1",userText:"重复",messages:[],characters:[c],provider});expect(first.character.relationship.intimacy).toBe(12);expect(second.duplicate).toBe(true);expect(fetchMock).toHaveBeenCalledTimes(1)});
 it("does not call the evaluator while strategy mode is disabled",async()=>{const c=character({chatSettings:{language:"中文",contextLimit:30,stream:false,strategyMode:{enabled:false}}});await db.characters.add(c);const fetchMock=vi.fn();vi.stubGlobal("fetch",fetchMock);const result=await evaluateStrategyInteraction({character:c,sourceId:"m1",userText:"你好",messages:[],characters:[c],provider:{...defaultProvider, networkMode: "direct" as const,apiKey:"test"}});expect(result.changed).toBe(false);expect(fetchMock).not.toHaveBeenCalled()});
 it("leaves relationship data unchanged when evaluation format fails",async()=>{const c=character();await db.characters.add(c);vi.stubGlobal("fetch",vi.fn(async()=>new Response(JSON.stringify({choices:[{message:{content:"not json"}}]}),{status:200,headers:{"Content-Type":"application/json"}})));await expect(evaluateStrategyInteraction({character:c,sourceId:"bad",userText:"你好",messages:[],characters:[c],provider:{...defaultProvider, networkMode: "direct" as const,apiKey:"test"}})).rejects.toBeTruthy();expect((await db.characters.get("c"))?.relationship.intimacy).toBe(10)}); it("saves confession bubbles only once transactionally",async()=>{await db.characters.add(character({relationship:{intimacy:100,trust:100,mood:"期待",recentEvents:[]}}));await db.conversations.add(conversation);const first=await saveConfessionMessages({characterId:"c",conversationId:"v",parts:["我喜欢你","可以和我在一起吗？"],provider:defaultProvider}),second=await saveConfessionMessages({characterId:"c",conversationId:"v",parts:["重复表白"],provider:defaultProvider});expect(first).toHaveLength(2);expect(second).toHaveLength(0);expect((await db.characters.get("c"))?.relationship.confessionTriggeredAt).toBeTypeOf("number");expect(await db.messages.count()).toBe(2)});
});
